import type { ServicePageContent } from "./types";

const cataractComparison = {
  title: "Choose the",
  accent: "Vision You Want",
  body: "The lens you choose shapes the rest of your life. Want to put your glasses away for good? There's a lens for that. Happy using readers? That works too. Here's the honest, side-by-side comparison — no pressure, no up-sell.",
  features: [
    "Lens Design",
    "Distance vision",
    "Reading (near)",
    "Computer (intermediate)",
    "Corrects astigmatism",
    "Glasses needed after surgery",
    "Night vision / halos",
    "Insurance / cost",
    "Best for",
    // "Typical starting cost (per eye)",
  ],
  columns: [
    { key: "monofocal", title: "Monofocal", subtitle: "Standard Lens", image: "/assets/monofocal.png", values: ["Excellent", "Needs glasses", "Limited", "No", "Usually needed", "Minimal risk", "Usually covered", "Budget conscious; happy to wear glasses"] },
    { key: "edof", title: "EDOF IOL", subtitle: "Extended Depth of Focus", image: "/assets/cataract/edof.png", values: ["Excellent", "Needs glasses", "Clear", "In toric variants", "Reduced dependency", "Minimal glare & halos", "Premium lens option", "Distance-to-intermediate clarity"] },
    { key: "toric", title: "Toric", subtitle: "For Astigmatism", image: "/assets/toric.png", values: ["Excellent", "Needs glasses", "Limited", "Yes", "Reduced need", "Minimal risk", "~ Partial coverage", "Patients with astigmatism"] },
    { key: "trifocal", title: "Trifocal / Multifocal", subtitle: "Premium Lens", image: "/assets/trifocal2.png", popular: true, highlighted: true, values: ["Excellent", "Clear", "Clear", "~ Varies", "Rarely needed", "~ Brief adjustment", "Premium", "Spectacle-free living"] },
  ],
  noteTitle: "A note from the Eye Surgeon:",
  noteText: 'The "best" lens is the one that matches your eyes, your prescription, and how you live your life. We do a detailed evaluation before recommending anything — and we will always explain why.',
  cta: "Get a Personalised Lens Recommendation",
};

const classicComparison = {
  title: "Choose the Vision Correction Option",
  accent: "That Fits Your Eyes",
  body: "There is no single best procedure for everyone. The right option depends on your eye power, corneal thickness, dry eye status, lifestyle, and long-term safety. Shanti EyeTech helps you understand your options clearly before you decide.",
  features: ["Procedure View", "Best For", "How It Works", "Recovery", "Glasses Dependency", "Dry Eye Consideration", "Suitable for Everyone?", "Doctor Advice Needed?"],
  columns: [
    { key: "lasik", title: "LASIK", subtitle: "Most Popular", image: "/assets/lasik1.png", values: ["Common spectacle removal cases", "Laser reshapes cornea after creating a flap", "Usually quick", "Reduced significantly", "Needs evaluation", "No", "Yes"] },
    { key: "smile", title: "SMILE", subtitle: "Flapless Laser", image: "/assets/smile1.png", values: ["Suitable candidates wanting flapless laser option", "Laser removes a small lenticule through tiny incision", "Usually quick", "Reduced significantly", "Often considered in selected cases", "No", "Yes"] },
    { key: "prk", title: "PRK", subtitle: "Surface Laser", image: "/assets/prk1.png", values: ["Thin cornea / selected cases", "Surface laser treatment without flap", "Slower than LASIK/SMILE", "Reduced significantly", "Depends on eye condition", "No", "Yes"] },
    { key: "icl", title: "ICL", subtitle: "Implantable Lens", image: "/assets/icl1.png", highlighted: true, values: ["High power or unsuitable cornea cases", "Implantable lens placed inside eye", "Usually quick", "Reduced significantly", "Depends on eye condition", "No", "Yes"] },
  ],
  noteTitle: "A note from the Eye Surgeon:",
  noteText: "The best procedure is not the most popular one. The best procedure is the one that is safest for your eyes, your cornea, your power, and your lifestyle. That is why we do a detailed evaluation before recommending anything.",
  cta: "Get My Personalised Vision Correction Recommendation",
};

const classicContent: ServicePageContent = {
  kind: "classic",
  navService: "lasik",
  hero: {
    eyebrow: "BLADE-FREE LASIK",
    title: "Freedom From Glasses",
    accent: "Starts Here",
    text: "Experience the clarity of life without glasses or contact lenses. Our advanced blade-free LASIK technology delivers precise, predictable results with quick recovery.",
    image: "/assets/lasik/lasik-banner.png",
    metrics: [
      { value: "49K+", label: "LASIK Procedures" },
      { value: "98%", label: "Success Rate" },
      { value: "24hrs", label: "Quick Recovery" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti EyeTech for LASIK",
    body: "Combining advanced technology with personalized care for optimal vision correction results",
    items: [
      { icon: "award", title: "Award-Winning Excellence", text: "Recognized nationally for refractive surgery outcomes" },
      { icon: "zap", title: "Blade-Free Technology", text: "Advanced femtosecond laser for precision and safety" },
      { icon: "users", title: "Experienced Specialists", text: "Over 25 years of LASIK surgical expertise" },
      { icon: "heart", title: "Personalized Treatment", text: "Custom wavefront-guided procedures for your eyes" },
      { icon: "clock", title: "Quick Recovery", text: "Most patients resume normal activities within 24 hours" },
      { icon: "shield", title: "Comprehensive Care", text: "Lifetime post-operative support and monitoring" },
      { icon: "eye", title: "All-Laser LASIK", text: "No blades involved in any part of the procedure" },
      { icon: "star", title: "Trusted by Thousands", text: "49,999+ successful LASIK procedures performed" },
    ],
  },
  intro: {
    eyebrow: "THE PROCEDURE",
    title: "What is",
    accent: "LASIK?",
    backgroundImage: "/assets/lasik/lasikbg.jpeg",
    paragraphs: [
      "LASIK (Laser-Assisted In Situ Keratomileusis) is the most advanced and popular laser vision correction procedure available today. It permanently reshapes the cornea to correct refractive errors and reduce dependence on glasses or contact lenses.",
      "Using state-of-the-art femtosecond laser technology, the procedure creates a thin corneal flap, then precisely reshapes the underlying corneal tissue with an excimer laser to correct your vision. The entire process takes just 15-20 minutes for both eyes.",
    ],
    callout: {
      title: "Quick & Comfortable",
      text: "The procedure is virtually painless with numbing eye drops, and most patients experience improved vision within 24 hours.",
    },
    lasikImages: {
      patient: "/assets/lasik/lasik-procedure.webp",
      room: "/assets/lasik/lasik-machine.webp",
      eye: "/assets/whatlasik3.png",
    },
  },
  eligibility: {
    eyebrow: "ELIGIBILITY",
    title: "Is LASIK",
    accent: "Right for You?",
    body: "You may be a good candidate for LASIK if you meet the following criteria:",
    backgroundImage: "/assets/lasik/lasikrightbg.jpeg",
    checks: ["At least 18 years of age", "Have stable vision prescription", "Have healthy eyes free from disease", "Tired of wearing glasses or contact lenses", "Have myopia (nearsightedness)", "Have hyperopia (farsightedness)", "Have astigmatism"],
    note: "A comprehensive eye examination by our specialists is required to determine your final suitability for LASIK surgery.",
    image: "/assets/lasik/lasik_right.jpeg",
  },
  treatmentOptions: {
    eyebrow: "TREATABLE CONDITIONS",
    title: "Conditions LASIK",
    accent: "Can Correct",
    body: "Our advanced LASIK technology effectively treats the most common refractive errors",
    options: [
      { image: "/assets/lasik/myopia.jpeg", title: "Myopia", tag: "NEARSIGHTEDNESS", text: "Difficulty seeing distant objects clearly. LASIK flattens the cornea to correct focus." },
      { image: "/assets/lasik/hyperopia1.jpeg", title: "Hyperopia", tag: "FARSIGHTEDNESS", text: "Difficulty seeing nearby objects. LASIK steepens the cornea for better near vision." },
      { image: "/assets/lasik/astigmatism1.jpeg", title: "Astigmatism", tag: "BLURRED VISION", text: "Irregular cornea shape causing blurred vision. LASIK smooths the cornea for clear focus." },
    ],
  },
  comparison: classicComparison,
  benefits: {
    eyebrow: "ADVANTAGES",
    title: "Benefits of",
    accent: "LASIK Surgery",
    items: [
      { image: "/assets/lasik/quick_recovery.jpeg", title: "Quick Recovery Time", description: "Most patients return to normal activities within 24 hours with minimal discomfort." },
      { image: "/assets/lasik/long_lasting.jpeg", title: "Long-Lasting Results", description: "LASIK provides permanent vision correction that can last a lifetime." },
      { image: "/assets/lasik/vision_journey.jpeg", title: "Improved Quality of Life", description: "Freedom from glasses and contacts opens up new lifestyle possibilities." },
      { image: "/assets/lasik/improve_quality.jpeg", title: "Cost-Effective Solution", description: "Save money long-term by eliminating glasses, contacts, and solutions." },
      { image: "/assets/lasik/lasik-eye.webp", title: "Enhanced Sports Performance", description: "Participate in activities without worrying about glasses or contacts." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real stories from real patients who transformed their vision with LASIK",
    items: [
      { quote: "Best decision I ever made! I can finally wake up and see clearly without reaching for glasses. The procedure was quick and painless, and Dr. Kumar made me feel completely comfortable throughout.", name: "Priya Sharma", meta: "LASIK Surgery - 29 years" },
      { quote: "I was nervous about the surgery, but the team at Shanti EyeTech was amazing. Within 24 hours, my vision was crystal clear. No more contacts, no more hassle!", name: "Raj Patel", meta: "Blade-Free LASIK - 34 years" },
      { quote: "As someone who wore glasses for 20 years, I cannot express how life-changing LASIK has been. The precision and care I received here exceeded all expectations.", name: "Anita Desai", meta: "Custom LASIK - 31 years" },
      { quote: "The laser procedure took less than 10 minutes with zero pain. Waking up with clear 20/20 vision feels like magic every single day!", name: "Amitabh Verma", meta: "Contoura LASIK - 33 years" },
      { quote: "Fantastic experience! The doctors were extremely reassuring and answered all my questions. I was back to work in two days.", name: "Kavita Rao", meta: "Femto LASIK - 27 years" },
      { quote: "No more fogged glasses while cooking or working out. LASIK at Shanti EyeTech completely elevated my lifestyle and confidence.", name: "Deepak Joshi", meta: "Blade-Free LASIK - 36 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "LASIK Care",
    accent: "FAQs",
    cardTitle: "Have More Questions?",
    cardText: "Our LASIK specialists are here to answer all your questions and help you determine if LASIK is right for you.",
    items: [
      { question: "Is LASIK surgery painful?", answer: "No, LASIK is virtually painless. We use numbing eye drops during the procedure, so you only feel slight pressure. Most patients report minimal discomfort that resolves within hours." },
      { question: "How long does LASIK surgery take?", answer: "The laser procedure itself takes only 10 to 15 minutes for both eyes. Plan to be at our center for about 1.5 to 2 hours total on surgery day." },
      { question: "When will I be able to see clearly after LASIK?", answer: "Most patients notice significantly improved vision within 24 hours. Full visual stabilization typically occurs over a few weeks." },
      { question: "Are the results of LASIK permanent?", answer: "Yes, LASIK permanently reshapes the cornea to correct your current prescription." },
      { question: "What is the recovery time after LASIK?", answer: "Most patients return to work and normal daily activities within 24 to 48 hours after the procedure." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "Transform your life with LASIK surgery. Our expert team is ready to guide you through every step of your journey to clear, glasses-free vision.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "LASIK",
    badgeTitle: "20/20",
    badgeSubtitle: "Clear Vision Awaits",
    checkTitle: "Free Pre-Operative Assessment",
    checkSubtitle: "Comprehensive evaluation to determine your LASIK candidacy",
  },
};

const cataractContent: ServicePageContent = {
  kind: "cataract",
  navService: "cataract",
  hero: {
    eyebrow: "ADVANCED CATARACT CARE",
    title: "Restore Clear Vision.",
    accent: "Rediscover Everyday Life.",
    text: "Modern cataract surgery safely restores your vision, helping you regain independence and enjoy life's precious moments with clarity and confidence.",
    image: "/assets/cataract/cataract-banner.png",
    metrics: [
      { value: "49K+", label: "Cataract Surgeries" },
      { value: "98%", label: "Success Rate" },
      { value: "Same Day", label: "Procedure" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti EyeTech for Cataract Care",
    body: "Trusted expertise and compassionate care for safe, effective cataract treatment",
    items: [
      { icon: "award", title: "Expert Surgeons", text: "25+ years of specialized cataract surgery experience" },
      { icon: "zap", title: "Advanced Technology", text: "State-of-the-art equipment for precision and safety" },
      { icon: "users", title: "Personalized Care", text: "Customized treatment plans for your unique needs" },
      { icon: "heart", title: "Compassionate Team", text: "Dedicated support throughout your journey" },
      { icon: "clock", title: "Quick Recovery", text: "Most patients resume activities within days" },
      { icon: "shield", title: "Comprehensive Support", text: "Lifetime post-operative care and monitoring" },
      { icon: "eye", title: "Premium IOL Options", text: "Multiple lens choices for optimal vision correction" },
      { icon: "star", title: "Proven Results", text: "49,999+ successful cataract procedures" },
    ],
  },
  intro: {
    eyebrow: "UNDERSTANDING CATARACTS",
    title: "What is a",
    accent: "Cataract?",
    backgroundImage: "/assets/cataract/whatisbg.jpeg",
    paragraphs: [
      "A cataract is a clouding of the eye's natural lens, which lies behind the iris and pupil. This lens works like a camera lens, focusing light onto the retina to produce clear images.",
      "As we age, proteins in the lens can clump together, causing the lens to become cloudy. This cloudiness prevents light from passing through clearly, resulting in blurred or dim vision, difficulty with glare, and reduced color perception.",
    ],
    image: "/assets/cataract/whatiscataract.jpeg",
    callout: {
      title: "Good News",
      text: "Cataracts are treatable. Modern cataract surgery is one of the safest and most successful procedures, restoring clear vision and improving quality of life for millions of patients worldwide.",
    },
  },
  eligibility: {
    eyebrow: "ELIGIBILITY",
    title: "When Should You",
    accent: "Consider Surgery?",
    body: "Cataract surgery may be recommended if you experience any of the following:",
    backgroundImage: "/assets/cataract/considersurgerybg.jpeg",
    checks: ["Vision interferes with daily activities", "Glasses no longer improve your vision", "Difficulty reading or driving safely", "Glare or halos around lights at night", "Cataracts are affecting your independence", "Your specialist recommends treatment"],
    note: "Only your eye care specialist can determine if cataract surgery is right for you. Schedule a comprehensive evaluation to discuss your options.",
    image: "/assets/cataract-chair.webp",
  },
  treatmentOptions: {
    eyebrow: "LENS OPTIONS",
    title: "Our Advanced",
    accent: "Cataract Care",
    body: "Types of Intraocular Lenses (IOLs) - Choose the best option for your lifestyle",
    options: [
      { image: "/assets/cataract/monofocal.jpeg", title: "Standard Monofocal", tag: "SINGLE FOCUS LENS", text: "Provides clear vision at one distance (usually far). Reading glasses may still be needed for close work.", bullets: ["Clear distance vision", "Covered by insurance", "Proven reliability"] },
      { image: "/assets/cataract/multifocal.jpeg", title: "Premium Multifocal", tag: "MULTIPLE FOCUS LENS", text: "Enables clear vision at multiple distances - near, intermediate, and far - reducing dependence on glasses.", bullets: ["Multiple focal points", "Reduced glasses dependency", "Enhanced lifestyle"] },
      { image: "/assets/cataract/edof-options.png", title: "EDOF IOL", tag: "EXTENDED DEPTH OF FOCUS", text: "Provides a continuous, seamless range of clear vision from distance to intermediate, with minimal glare and enhanced night vision.", bullets: ["Seamless distance to intermediate vision", "Reduced glare & halos at night", "Natural visual continuity"] },
      { image: "/assets/cataract/toric.jpeg", title: "Toric Lens", tag: "ASTIGMATISM CORRECTION", text: "Specially designed to correct astigmatism while providing clear distance vision in one procedure.", bullets: ["Corrects astigmatism", "Sharper clarity", "Single procedure"] },
    ],
  },
  comparison: cataractComparison,
  benefits: {
    eyebrow: "ADVANTAGES",
    title: "Benefits of Modern",
    accent: "Cataract Surgery",
    items: [
      { image: "/assets/cataract/cataractbenefit2.jpeg", title: "Improved color perception" },
      { image: "/assets/cataract/cataractbenefit1.jpeg", title: "Clearer, brighter vision" },
      { image: "/assets/cataract/cataractbenefit3.jpeg", title: "Better quality of life" },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients who restored their vision with cataract surgery",
    items: [
      { quote: "After years of struggling with cloudy vision, I can finally see my grandchildren clearly. The surgery was painless and recovery was quick. Dr. Kumar and the team made me feel comfortable every step of the way.", name: "Ramesh Kumar", meta: "Cataract Surgery - 68 years" },
      { quote: "I was nervous about surgery, but the results exceeded my expectations. Colors are vibrant again, and I can read without strain. I wish I had done this sooner!", name: "Lakshmi Devi", meta: "Premium IOL Surgery - 72 years" },
      { quote: "Both my eyes were treated with such precision and care. The difference is life-changing. I can drive confidently again and enjoy my hobbies. Highly recommended!", name: "Suresh Patel", meta: "Bilateral Cataract Surgery - 65 years" },
      { quote: "The advanced lens option restored my distance and reading vision seamlessly. I haven't worn glasses in months. Truly outstanding care by Shanti EyeTech!", name: "Sunita Agarwal", meta: "Multifocal IOL Surgery - 61 years" },
      { quote: "From pre-op consultation to post-op checkups, the staff were incredibly kind and professional. The procedure was smooth and completely pain-free.", name: "Vikram Malhotra", meta: "Laser Cataract Surgery - 70 years" },
      { quote: "I had cataracts in both eyes and was hesitant to undergo surgery. Dr. Solanki & team made the entire experience easy and comforting. My vision is 20/20 now!", name: "Meena Sharma", meta: "Cataract Surgery - 66 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Cataract Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Cataracts?",
    cardText: "Our cataract specialists are here to answer your questions and guide you through your treatment options.",
    items: [
      { question: "How do I know if I have cataracts?", answer: "Common signs include cloudy or blurry vision, difficulty seeing at night, sensitivity to light, seeing halos around lights, fading colors, and frequent changes in glasses prescription. A comprehensive eye examination can confirm cataracts." },
      { question: "Is cataract surgery safe?", answer: "Cataract surgery is one of the safest and most frequently performed surgical procedures in the world, with success rates over 98%." },
      { question: "How long does cataract surgery take?", answer: "The procedure itself typically takes only 15 to 20 minutes per eye. You will spend about 2 hours at the center total for prep and recovery." },
      { question: "Will I need glasses after cataract surgery?", answer: "It depends on the type of intraocular lens (IOL) you choose. Premium multifocal or trifocal lenses can reduce or eliminate your need for glasses." },
      { question: "What is the recovery time?", answer: "Most patients experience clearer vision within 24 to 48 hours and resume normal daily activities within a few days." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "Restore your clear vision and rediscover life's precious moments. Our experienced team is ready to guide you through safe, effective cataract treatment.",
    image: "/assets/cataract-chair.webp",
    serviceLabel: "treatment",
  },
};

const retinaContent: ServicePageContent = {
  kind: "retina",
  navService: "retina",
  hero: {
    eyebrow: "EARLY DETECTION & PREVENTION",
    title: "Preserve Your Vision.",
    accent: "Cherish Every Moment.",
    text: "Your retina is essential for the vision you rely on every day. Early detection and expert care can help protect it from serious, vision-threatening conditions.",
    image: "/assets/retina/retina-banner.png",
    metrics: [
      { value: "25+ yrs", label: "Retina Expertise" },
      { value: "98%", label: "Success Rate" },
      { value: "Essential", label: "Early Detection" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti EyeTech",
    body: "Specialized expertise in early detection and long-term retinal management",
    items: [
      { icon: "01", title: "Doctor-led eye care", text: "Every consultation handled by an experienced ophthalmologist" },
      { icon: "02", title: "Advanced technology", text: "Modern diagnostic and surgical equipment" },
      { icon: "03", title: "Patient-friendly environment", text: "A calm, peaceful, reassuring space" },
      { icon: "04", title: "Personalised Attention", text: "Treatment plans tailored to your needs" },
      { icon: "05", title: "Affordable solutions", text: "Quality care at accessible prices" },
      { icon: "06", title: "Central Indore location", text: "Easily reachable from across the city" },
      { icon: "07", title: "Trained paramedical staff", text: "Qualified team supporting you" },
      { icon: "08", title: "Comprehensive services", text: "All major eye care under one roof" },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Retina?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "The retina is the light-sensitive layer at the back of the eye that captures images and sends signals to the brain.",
      "Damage to the retina can lead to partial or total vision loss if not detected and treated early.",
    ],
    image: "/assets/retina/retina-exam.webp",
    retinaImages: {
      top: "/assets/retina/light_senstive.jpeg",
      bottom: "/assets/retina2.png",
    },
    callout: {
      title: "Retina care",
      text: "focuses on diagnosing and treating diseases that affect the retina, macula, and blood vessels at the back of the eye.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider Evaluation?",
    body: "Watch out for these warning signs and schedule a comprehensive evaluation if they occur.",
    checks: ["Blurred or distorted vision", "Floaters or dark spots in vision", "Difficulty seeing in low light", "Loss of peripheral (side) vision", "Diabetes or high blood pressure"],
    note: "Early evaluation is key: If you experience any of these symptoms or have risk factors, schedule a comprehensive retinal examination.",
    image: "/assets/retina/retina-exam.webp",
    warningImages: [
      { image: "/assets/retina/low-light.webp", label: "Blurred Vision" },
      { image: "/assets/retina/dark_spot.jpeg", label: "Dark Spots" },
      { image: "/assets/retina/low_vision.jpeg", label: "Low Light" },
      { image: "/assets/retina/side_vision.jpeg", label: "Side Vision" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Retina Care &",
    accent: "Treatment Options",
    body: "Advanced, precise care for better outcomes.",
    options: [
      { image: "/assets/retina/retina_surgery.jpeg", title: "Retina Surgery", tag: "ADVANCED CARE", text: "Advanced surgical solutions for complex retinal conditions." },
      { image: "/assets/retina/laser_therapy.jpeg", title: "Laser Therapy", tag: "TARGETED TREATMENT", text: "Targeted laser treatment to seal leaking retinal tears, reduce swelling, and protect vision." },
      { image: "/assets/retina/medical_management.jpeg", title: "Medical Management", tag: "PERSONALISED PLAN", text: "Medications and injections to manage retinal conditions and reduce swelling." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Retina Care",
    body: "Preserve your vision",
    items: [
      { image: "/assets/retina/active-life.webp", title: "Maintain an active life" },
      { image: "/assets/retina/preserve-vision.webp", title: "Preserve your vision" },
      { image: "/assets/retina/independent-life.webp", title: "Live Independently" },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients who protected their sight with retina care",
    items: [
      { quote: "After battling with vision loss for years, I finally found a solution. My eye health has improved significantly, and I'm able to see clearly again. Thank you, Shanti EyeTech!", name: "Girish Gole", meta: "Retina Evaluation - 61 years" },
      { quote: "Early retina care helped protect my sight. The doctors were calm, precise, and explained every scan and treatment option clearly.", name: "Jyoti Carson", meta: "Retina Care - 58 years" },
      { quote: "My diabetes had started affecting my eyes. Regular retina treatment helped me stay independent and confident with my vision.", name: "Suresh Sharma", meta: "Diabetic Retina Care - 64 years" },
      { quote: "State-of-the-art retina imaging equipment and deeply knowledgeable specialists. They saved my vision from retinal detachment.", name: "Sanjay Gupta", meta: "Retinal Laser Therapy - 55 years" },
      { quote: "Outstanding diagnostic accuracy and compassionate treatment. I am deeply thankful to Dr. Solanki and the entire retina team.", name: "Radhika Kulkarni", meta: "Macular Care - 69 years" },
      { quote: "Very thorough examination and gentle procedure. My vision has remained stable and clear thanks to timely intervention.", name: "Harish Chandra", meta: "Anti-VEGF Treatment - 73 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Retina Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Retina Care?",
    cardText: "Our specialists are here to answer your questions and guide you through your treatment options.",
    items: [
      { question: "How do I know if I have cataracts?", answer: "Common signs include cloudy or blurry vision, difficulty seeing at night, sensitivity to light, seeing halos around lights, fading colors, and frequent changes in glasses prescription. A comprehensive eye examination can confirm cataracts." },
      { question: "Is cataract surgery safe?", answer: "Treatment is recommended only after a detailed evaluation. Our specialists use modern technology and established clinical safety protocols." },
      { question: "How long does cataract surgery take?", answer: "Most consultations take 30-45 minutes. Some advanced diagnostic tests may require a little longer." },
      { question: "Will I need glasses after cataract surgery?", answer: "Our team can help you understand available insurance and payment options before treatment." },
      { question: "What is the recovery time?", answer: "Most patients experience clearer vision within 24 to 48 hours and resume normal daily activities within a few days." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "Restore your clear vision and rediscover life's precious moments. Our experienced team is ready to guide you through safe, effective cataract treatment.",
    image: "/assets/retina-chair.webp",
    serviceLabel: "retina care",
  },
};

const glaucomaContent: ServicePageContent = {
  kind: "glaucoma",
  navService: "glaucoma",
  hero: {
    eyebrow: "GLAUCOMA CARE",
    title: "Protect Your Vision",
    accent: "Before Glaucoma Takes It Away",
    text: "Glaucoma can gradually damage the optic nerve, often without noticeable symptoms in its early stages. Timely screening, regular monitoring and appropriate treatment can help protect your remaining vision.",
    image: "/assets/glaucoma/glaucoma-banner.png",
    metrics: [
      { value: "Silent", label: "Early Stages" },
      { value: "40+", label: "Routine Screening Age" },
      { value: "24/7", label: "Emergency Eye Care" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti EyeTech",
    accent: "for Glaucoma Care?",
    body: "Detailed assessment and long-term monitoring focused on protecting optic nerve health.",
    items: [
      { icon: "01", title: "Detailed Glaucoma Evaluation", text: "Assessment of eye pressure, optic nerve health and other risk factors to identify signs of glaucoma." },
      { icon: "02", title: "Optic Nerve Assessment", text: "Careful evaluation of the optic nerve to detect and monitor glaucoma-related changes." },
      { icon: "03", title: "Visual Field Testing", text: "Assessment of peripheral vision to identify functional vision loss associated with glaucoma." },
      { icon: "04", title: "Regular Progression Monitoring", text: "Follow-up examinations help track changes and determine whether treatment needs adjustment." },
      { icon: "05", title: "Personalised Treatment Planning", text: "Management is planned according to the type and severity of glaucoma, eye pressure and individual risk factors." },
      { icon: "06", title: "Medical, Laser & Surgical Care", text: "Treatment options may include eye drops, laser procedures or surgery depending on clinical findings." },
    ],
  },
  intro: {
    eyebrow: "UNDERSTANDING GLAUCOMA",
    title: "What is",
    accent: "Glaucoma?",
    backgroundImage: "/assets/whatisbg.png",
    paragraphs: [
      "Glaucoma is a group of eye conditions that damage the optic nerve, which carries visual information from the eye to the brain.",
      "In many cases, glaucoma is associated with increased pressure inside the eye, although it can also occur when eye pressure is within the normal range.",
      "The condition can gradually affect peripheral vision and, if left untreated, may lead to irreversible vision loss. Because early glaucoma may produce few or no noticeable symptoms, routine eye examinations are important for people at increased risk.",
    ],
    image: "/assets/glaucoma/whatisglaucoma.png",
    callout: {
      title: "Important",
      text: "Vision loss from glaucoma cannot be recovered. Early detection through regular eye exams is essential to preserve your sight.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Glaucoma Evaluation?",
    body: "Know your risk factors and warning signs:",
    backgroundImage: "/assets/cataract/considersurgerybg.jpeg",
    checks: [
      "Family history of glaucoma",
      "Increased eye pressure",
      "Age-related increase in glaucoma risk",
      "Diabetes or certain other medical conditions",
      "Long-term corticosteroid use",
      "Previous eye injury or eye surgery",
      "Gradual loss of peripheral vision",
      "Halos around lights or unexplained visual changes",
    ],
    note: "Sudden severe eye pain, redness, headache, blurred vision, halos, nausea or vomiting can occur with acute angle-closure glaucoma and requires urgent medical attention.",
    image: "/assets/eye-check.webp",
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Glaucoma Care &",
    accent: "Treatment Options",
    body: "Glaucoma treatment focuses on controlling eye pressure and reducing the risk of further optic nerve damage. The appropriate approach depends on the type and stage of glaucoma.",
    options: [
      { image: "/assets/glaucoma/medical_management.png", title: "Medical Management", tag: "Eye Pressure Control", text: "Prescription eye drops or other medications may be used to lower eye pressure and help reduce the risk of further optic nerve damage." },
      { image: "/assets/glaucoma/laser_treatment.png", title: "Laser Treatment", tag: "Targeted Treatment", text: "Laser procedures may be recommended for certain types of glaucoma to improve fluid drainage or help control pressure within the eye." },
      { image: "/assets/glaucoma/glaucoma_surgery.png", title: "Glaucoma Surgery", tag: "Advanced Glaucoma Care", text: "When medications or laser treatment do not provide sufficient pressure control, surgical treatment may be considered to help lower eye pressure." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Glaucoma Care",
    body: "Timely glaucoma care helps protect remaining vision through careful pressure control and ongoing monitoring.",
    items: [
      { image: "/assets/glaucoma/protect_remaining.png", title: "Protect Remaining Vision", description: "Early diagnosis and appropriate management can help reduce the risk of further vision loss." },
      { image: "/assets/glaucoma/control_eye.png", title: "Control Eye Pressure", description: "Treatment aims to maintain eye pressure at a level considered appropriate for the individual patient." },
      { image: "/assets/glaucoma/monitor_optic.png", title: "Monitor Optic Nerve Health", description: "Regular examinations allow changes in the optic nerve to be identified and tracked over time." },
      { image: "/assets/glaucoma/preserve_peripheral.png", title: "Preserve Peripheral Vision", description: "Controlling glaucoma progression can help protect functional side vision for as long as possible." },
      { image: "/assets/glaucoma/long_term.png", title: "Plan Long-Term Eye Care", description: "Because glaucoma usually requires ongoing monitoring, regular follow-up helps treatment evolve with the condition." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients who chose regular glaucoma monitoring and care",
    items: [
      { quote: "My glaucoma was found during a routine checkup. The doctor explained everything clearly, and regular follow-ups have helped me stay confident.", name: "Mahesh Verma", meta: "Glaucoma Screening - 57 years" },
      { quote: "I had no symptoms, but my family history made me worried. Shanti EyeTech helped me understand my risk and start timely treatment.", name: "Rekha Jain", meta: "Glaucoma Care - 62 years" },
      { quote: "The team tracks my eye pressure carefully at every visit. I feel reassured because the plan is clear and practical.", name: "Sanjay Mehta", meta: "Pressure Monitoring - 65 years" },
      { quote: "I used to miss my drops often. The counselling helped me understand why consistency matters for protecting my vision.", name: "Nirmala Rao", meta: "Medical Management - 69 years" },
      { quote: "The consultation was calm and detailed. Every test result was explained in simple language.", name: "Arun Sharma", meta: "Optic Nerve Evaluation - 54 years" },
      { quote: "Regular glaucoma reviews have helped me continue driving and reading comfortably.", name: "Kusum Patel", meta: "Long-term Follow-up - 71 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Glaucoma Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Glaucoma?",
    cardText: "Our glaucoma care team can help you understand screening, risk factors, monitoring and treatment options.",
    items: [
      { question: "Can glaucoma be cured?", answer: "Damage to the optic nerve caused by glaucoma is generally irreversible. However, treatment can lower eye pressure and help slow or prevent further damage." },
      { question: "Does glaucoma always cause symptoms?", answer: "No. Open-angle glaucoma, the most common form, often develops gradually without noticeable symptoms during its early stages." },
      { question: "Is high eye pressure the same as glaucoma?", answer: "No. Some people have elevated eye pressure without optic nerve damage, while others can develop glaucoma despite pressure readings within the statistically normal range. Diagnosis requires a complete eye assessment." },
      { question: "Who should be screened for glaucoma?", answer: "Regular comprehensive eye examinations become particularly important with increasing age and for people with risk factors such as a family history of glaucoma, elevated eye pressure or certain medical and ocular conditions." },
      { question: "Will I need glaucoma treatment for life?", answer: "Glaucoma is usually a long-term condition requiring ongoing monitoring. The type and duration of treatment depend on the individual patient and how the condition responds." },
      { question: "Does every glaucoma patient need surgery?", answer: "No. Many patients are managed with medication or laser treatment. Surgery may be considered when adequate pressure control is not achieved or when clinically appropriate." },
      { question: "Can lost vision from glaucoma return after treatment?", answer: "Existing glaucoma-related optic nerve damage usually cannot be reversed. This is why early detection and prevention of additional damage are especially important." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Don't Wait for Glaucoma",
    accent: "to Affect Your Vision",
    text: "Glaucoma can progress quietly. If you have increased eye pressure, a family history of glaucoma or other risk factors, a comprehensive glaucoma evaluation can help assess your optic nerve health and determine whether monitoring or treatment is needed.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "glaucoma care",
    badgeTitle: "Early",
    badgeSubtitle: "Detection Matters",
    checkTitle: "Book a Glaucoma Consultation",
    checkSubtitle: "Comprehensive evaluation for pressure, optic nerve health and risk factors",
  },
};

const squintContent: ServicePageContent = {
  kind: "squint",
  navService: "squint",
  hero: {
    eyebrow: "SQUINT TREATMENT",
    title: "Helping Eyes Work",
    accent: "Better Together",
    text: "Squint, or strabismus, occurs when both eyes do not remain properly aligned and look in the same direction. Early evaluation can help identify the cause and determine the appropriate treatment, particularly in children.",
    image: "/assets/squint/squint-banner.png",
    metrics: [
      { value: "Early", label: "Detection Key" },
      { value: "25+ yrs", label: "Specialized Care" },
      { value: "24/7", label: "Emergency Support" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti EyeTech",
    accent: "for Squint Treatment?",
    body: "Specialized eye alignment evaluation and compassionate care for children and adults.",
    items: [
      { icon: "01", title: "Detailed Eye Alignment Evaluation", text: "Assessment of eye position, movement and coordination to understand the type and extent of squint." },
      { icon: "02", title: "Child-Friendly Eye Care", text: "A comfortable approach to examining and managing squint in children." },
      { icon: "03", title: "Vision & Amblyopia Assessment", text: "Evaluation for associated vision problems, including lazy eye, where clinically relevant." },
      { icon: "04", title: "Personalised Treatment Planning", text: "Treatment recommendations based on age, vision, eye alignment and the underlying cause." },
      { icon: "05", title: "Non-Surgical & Surgical Options", text: "Management may include glasses, amblyopia treatment or surgery depending on individual findings." },
      { icon: "06", title: "Regular Follow-Up Care", text: "Ongoing assessment to monitor vision development and eye alignment." },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Squint?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "Squint, medically known as strabismus, is a condition in which the two eyes are not properly aligned and may point in different directions.",
      "One eye may look straight while the other turns inward, outward, upward or downward. The deviation may be present all the time or appear only occasionally.",
      "Squint can occur in both children and adults. In children, timely assessment is particularly important because persistent misalignment can interfere with normal visual development and may be associated with amblyopia, commonly called lazy eye.",
    ],
    image: "/assets/squint/whatissquint1.png",
    retinaImages: {
      top: "/assets/squint/whatissquint1.png",
      bottom: "/assets/squint/whatissquint2.png",
    },
    callout: {
      title: "Squint Care",
      text: "focuses on assessing eye alignment, preserving visual function, and guiding timely intervention for both children and adults.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Squint Evaluation?",
    body: "Watch Out for These Signs",
    backgroundImage: "/assets/retina/retina_optionsbg.jpeg",
    checks: [
      "One eye turning inward or outward",
      "Eyes that do not appear properly aligned",
      "Squint that appears intermittently",
      "Child closing or covering one eye",
      "Tilting or turning the head while looking at objects",
      "Difficulty judging depth or coordinating both eyes",
      "Double vision, particularly in adults",
      "An eye deviation that appears suddenly",
    ],
    note: "A sudden new squint or new double vision in an adult should be medically evaluated promptly.",
    image: "/assets/squint/whatissquint1.png",
    warningImages: [
      { image: "/assets/squint/blur_vision.png", label: "Blurred Vision" },
      { image: "/assets/squint/intermittent_squint.png", label: "Intermittent Squint" },
      { image: "/assets/squint/head_tilting.png", label: "Head Tilting" },
      { image: "/assets/squint/double_vision.png", label: "Double Vision" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Squint Care &",
    accent: "Treatment Options",
    body: "Care is planned according to the type of squint, its cause, age and its effect on vision.",
    options: [
      { image: "/assets/squint/glasses_correction.png", title: "Glasses / Vision Correction", tag: "VISION CORRECTION", text: "Prescription glasses may help improve vision and, in certain types of squint, can also improve eye alignment." },
      { image: "/assets/squint/amblyopia_treatment.png", title: "Amblyopia Treatment", tag: "LAZY EYE CARE", text: "When one eye has reduced vision, treatment may be recommended to encourage visual development in the weaker eye." },
      { image: "/assets/squint/squint_surgery.png", title: "Squint Surgery", tag: "EYE ALIGNMENT", text: "When clinically indicated, surgery can adjust the eye muscles to improve the alignment of the eyes." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Squint Care",
    body: "Support visual development and eye alignment.",
    items: [
      { image: "/assets/squint/support_visual.png", title: "Support Visual Development", description: "Early care can be particularly important while a child's visual system is still developing." },
      { image: "/assets/squint/improve_eye.png", title: "Improve Eye Alignment", description: "Appropriate management can help improve the position and coordination of the eyes." },
      { image: "/assets/squint/address_associated.png", title: "Address Associated Lazy Eye", description: "Identifying amblyopia early provides an opportunity to manage reduced vision in the affected eye." },
      { image: "/assets/squint/improve_binocular.png", title: "Improve Binocular Function", description: "Where possible, treatment aims to support the ability of both eyes to work together." },
      { image: "/assets/squint/visual_confidence.png", title: "Build Visual Confidence", description: "Improved alignment and visual function can make everyday visual activities more comfortable." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients and parents who chose squint evaluation and care",
    items: [
      { quote: "We noticed our child's eye turning occasionally. The doctor made the exam so comfortable, and early treatment helped tremendously.", name: "Pooja Sharma", meta: "Pediatric Squint Care - 6 years" },
      { quote: "I was hesitant about adult squint correction, but the evaluation gave me full confidence. The alignment results exceeded my expectations.", name: "Vikas Verma", meta: "Adult Alignment Care - 32 years" },
      { quote: "Proper prescription glasses and visual therapy helped align my daughter's eyes without needing surgery.", name: "Sunita Agarwal", meta: "Vision Correction - 9 years" },
      { quote: "Thorough testing and clear explanation of our options. The team tracked vision improvement at every follow-up.", name: "Ramesh Joshi", meta: "Amblyopia Management - 7 years" },
      { quote: "Gentle, expert care for children. The entire staff ensured my son felt safe and happy during every visit.", name: "Meena Patel", meta: "Squint Evaluation - 5 years" },
      { quote: "Timely diagnosis helped address lazy eye early. We are so grateful to the specialists at Shanti EyeTech.", name: "Anand Gupta", meta: "Binocular Vision Care - 11 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Squint Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Squint?",
    cardText: "Our eye care team can help you understand squint evaluation, treatment options and care plans.",
    items: [
      { question: "What causes squint?", answer: "Squint can have several causes, including problems with eye-muscle control, refractive errors, differences in vision between the eyes or other underlying eye or neurological conditions." },
      { question: "Is squint common in children?", answer: "Squint can occur during childhood. Any persistent or recurring eye deviation should be evaluated rather than assuming the child will simply outgrow it." },
      { question: "Can squint cause lazy eye?", answer: "Yes. In some children, the brain may begin relying more heavily on one eye, which can result in reduced vision in the deviating eye." },
      { question: "Does every squint require surgery?", answer: "No. Treatment depends on the type and cause of the squint. Some patients may require glasses or amblyopia treatment, while surgery may be appropriate for others." },
      { question: "Can adults undergo squint treatment?", answer: "Yes. Adults with squint can also be evaluated for appropriate treatment depending on the cause, symptoms and eye alignment." },
      { question: "When should my child have a squint evaluated?", answer: "If you notice persistent, frequent or recurring misalignment of the eyes, an eye examination should be arranged. Sudden-onset squint should be assessed promptly." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Take the First Step Towards",
    accent: "Better Eye Alignment",
    text: "If you notice that your or your child’s eyes are not properly aligned, an eye examination can help identify the cause and determine the appropriate next step.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "squint treatment",
    badgeTitle: "Early",
    badgeSubtitle: "Evaluation Matters",
    checkTitle: "Book a Squint Evaluation",
    checkSubtitle: "Comprehensive assessment for eye position, movement and visual development",
  },
};

const keratoconusContent: ServicePageContent = {
  kind: "keratoconus",
  navService: "keratoconus",
  hero: {
    eyebrow: "KERATOCONUS CARE",
    title: "Protect Your Cornea.",
    accent: "Preserve Clearer Vision.",
    text: "Keratoconus causes the cornea to gradually thin and change shape, leading to distorted or blurred vision. Early evaluation and appropriate management can help monitor its progression and protect visual quality.",
    image: "/assets/keratoconus/keratoconus-banner.png",
    metrics: [
      { value: "Early", label: "Detection Key" },
      { value: "25+ yrs", label: "Specialized Care" },
      { value: "24/7", label: "Emergency Support" },
    ],
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti EyeTech",
    accent: "for Keratoconus Care?",
    body: "Detailed corneal evaluation and advanced monitoring to protect visual quality.",
    items: [
      { icon: "01", title: "Detailed Corneal Evaluation", text: "Careful assessment of the cornea to understand its shape, thickness and condition." },
      { icon: "02", title: "Early Detection & Monitoring", text: "Regular evaluation can help identify changes and monitor whether keratoconus is progressing." },
      { icon: "03", title: "Advanced Corneal Imaging", text: "Diagnostic assessment using corneal mapping and other investigations when clinically required." },
      { icon: "04", title: "Personalised Treatment Planning", text: "Care recommendations based on the stage of keratoconus, visual needs and progression." },
      { icon: "05", title: "Vision Rehabilitation Options", text: "Guidance on suitable glasses or contact-lens options depending on the condition." },
      { icon: "06", title: "Progression-Control Treatment", text: "Corneal cross-linking may be considered in appropriate patients to help slow or halt progression." },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Keratoconus?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "Keratoconus is a condition in which the normally rounded cornea becomes thinner and gradually develops a cone-like shape.",
      "The cornea is the transparent front surface of the eye and plays an important role in focusing light. When its shape becomes irregular, light may no longer focus properly on the retina, resulting in blurred or distorted vision.",
      "Keratoconus often begins during the teenage years or early adulthood and may progress differently from person to person. Regular monitoring is important to identify changes over time.",
    ],
    image: "/assets/keratoconus/whatiskeratoconus1.png",
    retinaImages: {
      top: "/assets/keratoconus/whatiskeratoconus2.png",
      bottom: "/assets/keratoconus/whatiskeratoconus1.png",
    },
    callout: {
      title: "Keratoconus Care",
      text: "focuses on detailed corneal assessment, preserving functional vision, and halting progression through timely management.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Keratoconus Evaluation?",
    body: "Watch Out for These Signs",
    backgroundImage: "/assets/retina/retina_optionsbg.jpeg",
    checks: [
      "Frequent changes in spectacle power",
      "Increasing blurred or distorted vision",
      "Difficulty seeing clearly even with glasses",
      "Increased sensitivity to bright light or glare",
      "Halos around lights, especially at night",
      "Ghosting or multiple images around objects",
      "Increasing astigmatism",
      "Family history of keratoconus",
    ],
    note: "If your spectacle prescription is changing frequently or your vision remains distorted despite correction, a detailed corneal evaluation may be recommended.",
    image: "/assets/keratoconus/frequent_power.png",
    warningImages: [
      { image: "/assets/keratoconus/frequent_power.png", label: "Frequent Power Change" },
      { image: "/assets/keratoconus/blurred_vision.png", label: "Blurred / Distorted Vision" },
      { image: "/assets/keratoconus/light_sesitivity.png", label: "Light Sensitivity" },
      { image: "/assets/keratoconus/halos.png", label: "Halos & Glare" },
      { image: "/assets/keratoconus/astigmatism.png", label: "Increasing Astigmatism" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Keratoconus Care &",
    accent: "Treatment Options",
    body: "Treatment depends on the severity of the condition, quality of vision and whether the keratoconus is progressing.",
    options: [
      { image: "/assets/keratoconus/glasses.png", title: "Glasses & Contact Lenses", tag: "VISION CORRECTION", text: "In earlier stages, spectacles or specialised contact lenses may help improve visual clarity by correcting the refractive error caused by the irregular cornea." },
      { image: "/assets/keratoconus/corneal-cross.png", title: "Corneal Cross-Linking (CXL)", tag: "PROGRESSION CONTROL", text: "Cross-linking is used in appropriate cases of progressive keratoconus to strengthen the corneal tissue and help reduce further progression." },
      { image: "/assets/keratoconus/advanced-corneal.png", title: "Advanced Corneal Management", tag: "ADVANCED CARE", text: "For patients with more advanced keratoconus, additional treatment or visual-rehabilitation options may be considered after detailed evaluation." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Keratoconus Care",
    body: "Detect progression early and preserve clear, functional vision.",
    items: [
      { image: "/assets/keratoconus/detect_progression.png", title: "Detect Progression Early", description: "Regular corneal evaluation can help identify changes before significant progression occurs." },
      { image: "/assets/keratoconus/preserve_functional.png", title: "Preserve Functional Vision", description: "Appropriate correction and management can help patients maintain better usable vision." },
      { image: "/assets/keratoconus/control_progression.png", title: "Control Progression", description: "In suitable progressive cases, cross-linking can help stabilise the cornea and reduce further deterioration." },
      { image: "/assets/keratoconus/improve_visual.png", title: "Improve Visual Quality", description: "Appropriate glasses or contact lenses can help manage blur and distortion caused by the irregular cornea." },
      { image: "/assets/keratoconus/plan-long-term.png", title: "Plan Long-Term Corneal Care", description: "Regular monitoring allows treatment decisions to be adjusted as the condition changes." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients who underwent corneal evaluation and keratoconus management",
    items: [
      { quote: "My spectacle prescription kept changing every few months. The corneal topography showed early keratoconus, and CXL stabilized my vision.", name: "Rahul Soni", meta: "Corneal Cross-Linking - 24 years" },
      { quote: "Specialty contact lenses completely restored my vision clarity. The corneal care team guided me every step of the way.", name: "Priya Nair", meta: "Visual Rehabilitation - 29 years" },
      { quote: "Early detection made all the difference. Regular corneal mapping keeps track of my eyes with total accuracy.", name: "Siddharth Mehta", meta: "Corneal Monitoring - 21 years" },
      { quote: "I was worried about night driving glare. The custom lens fitting made my visual quality clear and comfortable again.", name: "Anish Kapoor", meta: "Keratoconus Care - 31 years" },
      { quote: "Professional, thorough, and highly knowledgeable specialists in corneal health.", name: "Kavita Reddy", meta: "Astigmatism & Corneal Care - 27 years" },
      { quote: "Gave me complete clarity on why my vision was distorted and how to halt progression effectively.", name: "Deepak Sharma", meta: "Progression Control - 26 years" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Keratoconus Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Keratoconus?",
    cardText: "Our corneal care team can help you understand keratoconus evaluation, progression monitoring, and treatment options.",
    items: [
      { question: "What causes keratoconus?", answer: "The exact cause is not always known. Genetic and environmental factors may contribute, and keratoconus can sometimes run in families." },
      { question: "Does keratoconus always get worse?", answer: "Not necessarily. Progression varies between individuals. This is why periodic corneal evaluation and comparison of measurements are important." },
      { question: "Can glasses correct keratoconus?", answer: "Glasses may provide adequate vision in early keratoconus. As corneal irregularity increases, specialised contact lenses may provide better visual correction for some patients." },
      { question: "What is corneal cross-linking?", answer: "Corneal cross-linking is a procedure designed to strengthen corneal tissue. It is primarily intended to reduce or stop further progression rather than simply remove spectacle power." },
      { question: "Can LASIK be performed if I have keratoconus?", answer: "Keratoconus generally makes standard corneal laser vision-correction procedures such as LASIK unsuitable. A detailed corneal assessment is necessary before considering any refractive procedure." },
      { question: "Can keratoconus affect both eyes?", answer: "Yes. Keratoconus commonly affects both eyes, although its severity and progression may differ between them." },
      { question: "Why is early diagnosis important?", answer: "Detecting keratoconus early allows the ophthalmologist to monitor progression and consider treatment before more significant corneal changes occur." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE NEXT STEP",
    title: "Take the Next Step Towards",
    accent: "Protecting Your Cornea",
    text: "If you are experiencing frequent power changes, distorted vision or have been diagnosed with keratoconus, a detailed corneal evaluation can help determine its current stage and the appropriate next step.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "keratoconus care",
    badgeTitle: "Early",
    badgeSubtitle: "Diagnosis Matters",
    checkTitle: "Book a Corneal Evaluation",
    checkSubtitle: "Comprehensive assessment of corneal shape, thickness and visual quality",
  },
};

export const servicePages = {
  cataract: cataractContent,
  classic: classicContent,
  lasik: classicContent,
  retina: retinaContent,
  glaucoma: glaucomaContent,
  squint: squintContent,
  keratoconus: keratoconusContent,
};










