import type { ServicePageContent, TestimonialItem } from "./types";

// Real patient reviews (Google) not specific to one procedure — reused
// across the retina, glaucoma, squint, and keratoconus pages, which don't
// have enough procedure-specific reviews of their own yet.
const commonTestimonials: TestimonialItem[] = [
  { quote: "Our family recently had the opportunity to take laser and cataract surgery services at Shanti Eye Tech Hospital, and it was truly an amazing experience from start to finish. Dr. Amit Solanki and his dedicated staff went above and beyond in taking care of us. It's rare to find a place where advanced medical care meets such heartfelt compassion.", name: "Madan Agrawal", meta: "Patient Review" },
  { quote: "Dr. Solanki explained everything clearly, which gave us a lot of confidence and comfort. The surgery was successful, and the post-operative care was also very attentive. His professionalism, calm nature, and expertise truly stand out.", name: "Naman Agrawal", meta: "Patient Review" },
  { quote: "I had a very good experience at Shanti Eye Tech Clinic. Dr. Amit Solanki is extremely knowledgeable, patient, and attentive. He listened carefully to my concerns and explained the condition and treatment clearly, which made me feel very comfortable and confident.", name: "Sandeep Debnath", meta: "Patient Review" },
  { quote: "Dr amit solanki is master in his field. He properly replied to our queries and doubts before surgery. His cooperative and friendly nature makes us more comfortable. His team is also polite and friendly.", name: "Manish V Jain", meta: "Patient Review" },
  { quote: "Very well trained facilities and top surgeon to have surgery, and staff nature is very cooperative and well behaved. We are fully satisfied with our cataract surgery.", name: "Renuka Agrawal", meta: "Patient Review" },
  { quote: "Had a great experience. Sir explained everything in detail and has a very polite nature.", name: "Anjali Singh", meta: "Patient Review" },
  { quote: "Great experience and wonderful environment. Must visit for an eye checkup.", name: "Devendr Ghosar", meta: "Patient Review" },
];

// Reviews that don't reference a specific unrelated procedure (e.g. cataract
// or LASIK surgery) — used on pages like glaucoma where most of
// commonTestimonials would otherwise read as mismatched.
const generalCareTestimonials: TestimonialItem[] = [
  { quote: "I had a very good experience at Shanti Eye Tech Clinic. Dr. Amit Solanki is extremely knowledgeable, patient, and attentive. He listened carefully to my concerns and explained the condition and treatment clearly, which made me feel very comfortable and confident.", name: "Sandeep Debnath", meta: "Patient Review" },
  { quote: "Had a great experience. Sir explained everything in detail and has a very polite nature.", name: "Anjali Singh", meta: "Patient Review" },
  { quote: "Great experience and wonderful environment. Must visit for an eye checkup.", name: "Devendr Ghosar", meta: "Patient Review" },
];

const cataractComparison = {
  title: "Choose the",
  accent: "Vision You Want",
  body: "Looking to reduce your dependence on glasses? Different IOL options may support different visual needs.",
  features: [
    "Lens Design",
    "Distance vision",
    "Reading (near)",
    "Computer (intermediate)",
    "Corrects astigmatism",
    "Glasses needed after surgery",
    "Night vision / halos",
    "Insurance / cost",
    "Best for",
    // "Typical starting cost (per eye)",
  ],
  columns: [
    { key: "monofocal", title: "Monofocal", subtitle: "Standard Lens", image: "/assets/monofocal.png", values: ["Excellent", "Needs glasses", "Limited", "No", "Usually needed", "Night-vision effects vary", "Coverage varies", "Budget conscious; happy to wear glasses"] },
    { key: "edof", title: "EDOF IOL", subtitle: "Extended Depth of Focus", image: "/assets/cataract/edof.png", values: ["Excellent", "Needs glasses", "May offer clear vision", "In toric variants", "Some patients may still need glasses", "Night-vision effects vary", "Premium lens option", "Distance-to-intermediate clarity"] },
    { key: "toric", title: "Toric", subtitle: "For Astigmatism", image: "/assets/toric.png", values: ["Excellent", "Needs glasses", "Limited", "Yes", "Reduced need", "Night-vision effects vary", "Coverage varies", "Patients with astigmatism"] },
    { key: "trifocal", title: "Trifocal / Multifocal", subtitle: "Premium Lens", image: "/assets/trifocal2.png", popular: true, highlighted: true, values: ["Excellent", "May offer clear vision", "May offer clear vision", "~ Varies", "Some patients may still need glasses", "Night-vision effects vary", "Premium", "Reduced dependence on glasses for some patients"] },
  ],
  noteTitle: "A note from the Eye Surgeon:",
  noteText: 'The "best" lens is the one that matches your eyes, your prescription, and how you live your life. We do a detailed evaluation before recommending anything, and will always explain why. Insurance and cost coverage depends on your insurer, policy and the lens option chosen — please confirm details with our team and your insurer.',
  cta: "Get a Personalised Lens Recommendation",
};

const classicComparison = {
  title: "Choose the Vision Correction Option",
  accent: "That Fits Your Eyes",
  body: "There is no single best procedure for everyone. The right option depends on your eye power, corneal thickness, age, and lifestyle. Shanti Eye Tech helps you understand your options clearly before you decide.",
  features: ["Procedure View", "Best For", "How It Works", "Recovery", "Glasses Dependency", "Ideal Candidate", "Suitable for Everyone?", "Doctor Advice Needed?"],
  columns: [
    { key: "touchless-lasik", title: "Touchless LASIK", subtitle: "Laser Vision Correction", image: "/assets/lasik1.png", values: ["Common spectacle removal cases", "Bladeless, touchless laser creates a thin corneal flap, then reshapes the cornea", "Recovery varies", "May reduce glasses dependence", "Stable prescription, healthy cornea", "No", "Yes"] },
    { key: "smile", title: "SMILE", subtitle: "Flapless Laser", image: "/assets/lasik/smile-procedure.png", values: ["Suitable candidates wanting a flapless laser option", "Laser removes a small lenticule through a tiny incision", "Recovery varies", "May reduce glasses dependence", "Often considered in selected cases", "No", "Yes"] },
    { key: "prk", title: "PRK", subtitle: "Surface Laser", image: "/assets/lasik/prk-procedure.png", values: ["Thin cornea / selected cases", "Surface laser treatment without a corneal flap", "Recovery varies, typically slower than LASIK/SMILE", "May reduce glasses dependence", "Depends on eye condition", "No", "Yes"] },
    { key: "icl", title: "ICL", subtitle: "Implantable Collamer Lens", image: "/assets/icl1.png", values: ["Moderate to severe refractive errors", "Biocompatible lens placed behind the iris", "Recovery varies", "May reduce glasses dependence", "Thin corneas unsuitable for LASIK", "No", "Yes"] },
    { key: "prelex", title: "PRELEX", subtitle: "Presbyopic Lens Exchange", image: "/assets/lasik/prelex_procedure2.png", highlighted: true, values: ["Presbyopia, typically over 40", "Natural lens replaced with an artificial IOL", "Recovery varies, similar to cataract surgery", "May reduce glasses dependence", "Patients over 40 with refractive errors", "No", "Yes"] },
  ],
  noteTitle: "A note from the Eye Surgeon:",
  noteText: "The best procedure is not the most popular one. The best procedure is the one that matches your eyes, your cornea, your power, and your lifestyle. That is why we do a detailed evaluation before recommending anything. Your surgeon will discuss benefits, limitations and possible risks for each option.",
  cta: "Get My Personalised Vision Correction Recommendation",
};

const classicContent: ServicePageContent = {
  kind: "classic",
  navService: "lasik",
  hero: {
    eyebrow: "VISION CORRECTION",
    title: "Freedom From Glasses",
    accent: "Starts Here",
    text: "Explore vision-correction options that may reduce dependence on glasses or contact lenses, subject to detailed eye evaluation. Choose from Touchless LASIK, SMILE, PRK, ICL and PRELEX — advanced vision-correction procedures matched to your eyes and lifestyle.",
    image: "/assets/lasik/lasik-banner.png",
    metrics: [
      { value: "20+", label: "Years Experience" },
      { value: "49K+", label: "Successful Procedures" },
      { value: "97%", label: "Success Rate" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti Eye Tech for Freedom From Glasses",
    body: "Combining advanced technology with personalized care for optimal vision correction results",
    items: [
      { icon: "award", title: "Award-Winning Excellence", text: "Multiple awards and professional recognitions in ophthalmology." },
      { icon: "zap", title: "Multiple Advanced Options", text: "Touchless LASIK, SMILE, PRK, ICL and PRELEX under one roof" },
      { icon: "users", title: "Experienced Specialists", text: "Over 20 years of ophthalmology experience, with specialised LASIK/refractive surgical training." },
      { icon: "heart", title: "Personalized Treatment", text: "The right procedure recommended for your eyes, not the most popular one" },
      { icon: "clock", title: "Recovery Varies", text: "Recovery time differs by procedure and individual healing. Your surgeon will provide personalised activity guidance." },
      { icon: "shield", title: "Comprehensive Care", text: "Post-operative follow-up and monitoring as advised by your surgeon." },
      { icon: "eye", title: "Procedure-Specific Techniques", text: "The techniques and recovery considerations differ between laser, implantable-lens and lens-exchange procedures." },
      { icon: "star", title: "Trusted by Thousands", text: "49,999+ successful vision correction procedures performed" },
    ],
  },
  intro: {
    eyebrow: "THE PROCEDURES",
    title: "What is",
    accent: "Freedom From Glasses?",
    backgroundImage: "/assets/lasik/lasikbg.jpeg",
    paragraphs: [
      "Vision-correction procedures may reduce, and for some suitable patients remove, the need for glasses or contact lenses in daily activities. The appropriate option depends on your prescription, corneal measurements, age, eye health and visual needs.",
      "Freedom From Glasses covers several advanced procedures — <strong>Touchless LASIK</strong>, <strong>SMILE</strong> and <strong>PRK</strong> (laser vision correction), <strong>ICL</strong> (Implantable Collamer Lens), and <strong>PRELEX</strong> (Presbyopic Lens Exchange) — so your treatment can be matched precisely to your eyes, age and lifestyle.",
    ],
    callout: {
      title: "Which Option is Right for You?",
      text: "Laser-vision-correction and lens-based options are selected after detailed assessment. Your surgeon will discuss benefits, limitations and possible risks before recommending a procedure.",
    },
    lasikImages: {
      patient: "/assets/lasik/lasik-procedure.webp",
      room: "/assets/lasik/lasik-machine.webp",
      eye: "/assets/whatlasik3.png",
    },
  },
  eligibility: {
    eyebrow: "ELIGIBILITY",
    title: "Is Freedom From Glasses",
    accent: "Right for You?",
    body: "Eligibility is assessment-led and differs by procedure. General starting points include:",
    backgroundImage: "/assets/lasik/lasikrightbg.jpeg",
    checks: ["At least 18 years of age, for laser vision correction", "Have a stable vision prescription", "Have healthy eyes free from disease", "Interested in reducing dependence on glasses or contact lenses", "Moderate to severe refractive errors, or thin corneas unsuitable for LASIK — may be considered for ICL", "Over 40 and experiencing presbyopia — may be considered for PRELEX"],
    note: "A comprehensive eye examination by our specialists determines which procedure, if any, suits you best.",
    image: "/assets/lasik/lasik_right.jpeg",
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Vision Correction",
    accent: "Procedures",
    body: "Advanced procedures, matched to your eyes, prescription and lifestyle. The appropriate option depends on your prescription, corneal measurements, age, eye health and visual needs.",
    options: [
      { image: "/assets/lasik/touchless_lasik.png", title: "Touchless LASIK", tag: "LASER VISION CORRECTION", text: "A bladeless, flapless, touchless laser vision-correction option for suitable patients. Suitability is determined after detailed corneal evaluation." },
      { image: "/assets/lasik/smile-procedure.png", title: "SMILE", tag: "FLAPLESS LASER", text: "A minimally invasive, flapless laser procedure that removes a small lenticule of corneal tissue through a tiny incision. May be considered for suitable candidates after assessment." },
      { image: "/assets/lasik/prk-procedure.png", title: "PRK", tag: "SURFACE LASER", text: "A flapless surface laser treatment that reshapes the outer corneal surface directly. May be considered for select cases, including some thinner corneas, after assessment; recovery typically takes longer than LASIK or SMILE." },
      { image: "/assets/lasik/ICL.png", title: "ICL (Implantable Collamer Lens)", tag: "IMPLANTABLE LENS", text: "A thin, flexible lens made from biocompatible Collamer material, positioned behind the iris and in front of the natural lens. May be considered for suitable patients, including some with higher prescriptions or corneal characteristics that make laser correction less suitable." },
      { image: "/assets/lasik/PRELEX.png", title: "PRELEX (Presbyopic Lens Exchange)", tag: "LENS EXCHANGE", text: "Lens-exchange surgery, similar in technique to cataract surgery, that may be considered for suitable patients with presbyopia or refractive error. The lens choice and expected vision range are determined after evaluation." },
    ],
  },
  comparison: classicComparison,
  benefits: {
    eyebrow: "ADVANTAGES",
    title: "Benefits of",
    accent: "Freedom From Glasses",
    body: "Many suitable patients experience reduced dependence on glasses; age-related changes and individual outcomes vary.",
    items: [
      { image: "/assets/lasik/quick_recovery.jpeg", title: "Recovery Varies", description: "Recovery time differs by procedure and individual healing. Your surgeon will provide personalised activity guidance." },
      { image: "/assets/lasik/long_lasting.jpeg", title: "Results Over Time", description: "Many patients experience stable vision correction over time; individual outcomes and age-related changes vary." },
      { image: "/assets/lasik/vision_journey.jpeg", title: "Improved Quality of Life", description: "Reduced dependence on glasses or contacts can open up new lifestyle possibilities for many patients." },
      { image: "/assets/lasik/improve_quality.jpeg", title: "Vision Quality", description: "Vision quality, contrast and night vision may improve, depending on the procedure and individual healing." },
      { image: "/assets/lasik/lasik-eye.webp", title: "Customized to Your Eyes", description: "Each procedure and lens can be tailored to correct a wide range of prescriptions." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real stories from real patients who found freedom from glasses at Shanti Eye Tech",
    items: [
      { quote: "I got my sister's vision correction surgery (LASIK) done from Dr Amit Solanki, and it was a very smooth process overall. The doctor was very professional and explained the whole procedure and helped us make the right decision. The staff was also very friendly and supportive.", name: "Ashish Masih", meta: "Patient Review" },
      { quote: "I got touchless LASIK done by Dr Amit Solanki, and the experience was honestly great. He was super friendly, explained everything clearly, and made the whole thing feel easy. The clinic is clean, modern, and they did a really thorough job with all the tests. Definitely recommend!", name: "Dhruv Surana Jain", meta: "Patient Review" },
      { quote: "I got touchless robotic LASIK surgery done by Dr. Amit Solanki. He is very genuine and explains everything in detail. I had no issues post surgery. He and his staff were always available for help. I am extremely happy with the surgery.", name: "Rashi Dawar", meta: "Patient Review" },
      { quote: "Good experience — the doctor explained everything in detail and in a very friendly way. Throughout the LASIK surgery he was very supportive and kind. It was a good experience overall.", name: "Geetika Vishwakarma", meta: "Patient Review" },
      { quote: "Dr. Solanki is excellent at his skill and extremely kind and helpful. He walked me through every aspect of the LASIK treatment and answered every question patiently and with utmost integrity. Highly recommend!", name: "Shreya Mundra", meta: "Patient Review" },
      { quote: "I'm extremely happy and satisfied with my LASIK surgery performed by Dr. Amit Solanki. The friendly environment and the supportive nature of Dr. Amit as well as the staff made the whole experience very pleasant.", name: "Nainika Soni", meta: "Patient Review" },
      { quote: "Dr. Amit Solanki was a wonderful surgeon, and the staff was always helpful and kind. They ensured I had a smooth prep, surgery, and follow-up. I am so glad I chose them for my LASIK eye surgery and would highly recommend to anyone.", name: "Ishita Sheel", meta: "Patient Review" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Freedom From Glasses",
    accent: "FAQs",
    cardTitle: "Have More Questions?",
    cardText: "Our specialists are here to answer all your questions and help you determine which procedure is right for you.",
    items: [
      { question: "What is the difference between Touchless LASIK, SMILE, PRK, ICL and PRELEX?", answer: "Touchless LASIK uses a laser to create a thin corneal flap, then reshapes the cornea. SMILE is a flapless laser procedure using a small incision. PRK is a flapless surface laser treatment. ICL places a lens inside the eye without removing the natural lens, and may be considered for higher prescriptions or corneas unsuitable for laser correction. PRELEX replaces the natural lens and may be considered for suitable patients with presbyopia. Your specialist recommends the most appropriate option after a detailed evaluation, and will discuss benefits, limitations and possible risks." },
      { question: "Is Touchless LASIK painful?", answer: "Numbing eye drops are used during the procedure, so most patients feel slight pressure rather than pain. Individual experience and post-procedure discomfort can vary — your surgeon will discuss what to expect." },
      { question: "Who is a good candidate for ICL?", answer: "ICL may be considered for suitable patients, including some with higher prescriptions or corneal characteristics that make laser correction less suitable. Suitability is determined after a comprehensive eye examination." },
      { question: "Who is PRELEX recommended for?", answer: "PRELEX may be considered for suitable patients with presbyopia or refractive error, often but not exclusively over 40. The lens choice and expected vision range are determined after evaluation." },
      { question: "What is the recovery time for these procedures?", answer: "Recovery time differs by procedure and individual healing. Your surgeon will provide personalised activity guidance based on which procedure you undergo." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "Book a vision-correction evaluation. Our team can guide you through Touchless LASIK, SMILE, PRK, ICL and PRELEX options after a comprehensive eye examination.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "vision correction",
    checkTitle: "Comprehensive Evaluation",
    checkSubtitle: "Evaluation to help determine which procedure suits you best",
  },
};

const cataractContent: ServicePageContent = {
  kind: "cataract",
  navService: "cataract",
  hero: {
    eyebrow: "ADVANCED CATARACT CARE",
    title: "Restore Clear Vision.",
    accent: "Rediscover Everyday Life.",
    text: "Cataract surgery in Indore at Shanti Eye Tech is aimed at helping restore your vision, supporting greater independence and clarity in everyday life.",
    image: "/assets/cataract/cataract-banner.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "97%", label: "Success Rate" },
      { value: "Same Day", label: "Procedure" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti Eye Tech for Cataract Care",
    body: "Trusted expertise and compassionate care for safe, effective cataract treatment",
    items: [
      { icon: "award", title: "Expert Surgeons", text: "20+ years of ophthalmology experience, with specialized training in advanced phaco cataract surgery." },
      { icon: "zap", title: "Advanced Technology", text: "State-of-the-art equipment for precision and safety" },
      { icon: "users", title: "Personalized Care", text: "Customized treatment plans for your unique needs" },
      { icon: "heart", title: "Compassionate Team", text: "Dedicated support throughout your journey" },
      { icon: "clock", title: "Quick Recovery", text: "Recovery varies. Your ophthalmologist will advise when you can safely resume specific activities." },
      { icon: "shield", title: "Comprehensive Support", text: "Planned post-operative follow-up and monitoring as advised by your ophthalmologist." },
      { icon: "eye", title: "Premium IOL Options", text: "Multiple lens choices for optimal vision correction" },
      { icon: "star", title: "Proven Results", text: "49,999+ successful cataract procedures" },
    ],
  },
  intro: {
    eyebrow: "UNDERSTANDING CATARACTS",
    title: "What is a",
    accent: "Cataract?",
    backgroundImage: "/assets/cataract/whatisbg.jpeg",
    paragraphs: [
      "A cataract is a <strong>clouding of the eye's natural lens</strong>, which lies behind the iris and pupil. This lens works like a camera lens, focusing light onto the retina to produce clear images.",
      "As we age, <strong>proteins in the lens can clump together</strong>, causing the lens to become cloudy. This cloudiness prevents light from passing through clearly, resulting in <strong>blurred or dim vision, difficulty with glare, and reduced color perception</strong>.",
    ],
    image: "/assets/cataract/whatiscataract.jpeg",
    callout: {
      title: "Good News",
      text: "Cataracts are treatable. Modern cataract surgery is one of the safest and most successful procedures, and has helped improve vision and quality of life for many patients worldwide. As with any surgery, risks and expected results should be discussed with your ophthalmologist.",
    },
  },
  eligibility: {
    eyebrow: "ELIGIBILITY",
    title: "When Should You",
    accent: "Consider Surgery?",
    body: "Cataract surgery may be recommended if you experience any of the following. Cataracts become more common with age, but can occur earlier for other reasons.",
    backgroundImage: "/assets/cataract/considersurgerybg.jpeg",
    checks: ["Vision interferes with daily activities", "Glasses no longer improve your vision", "Difficulty reading or driving safely", "Glare or halos around lights at night", "Cataracts are affecting your independence", "Your specialist recommends treatment"],
    note: "Only your eye care specialist can determine if cataract surgery is right for you. Schedule a comprehensive evaluation to discuss your options.",
    image: "/assets/about/modern.jpeg",
  },
  treatmentOptions: {
    eyebrow: "LENS OPTIONS",
    title: "Our Advanced",
    accent: "Cataract Care",
    body: "Types of Intraocular Lenses (IOLs) - choose the option that may suit your lifestyle. Coverage depends on your insurer, policy and lens option - please confirm with our team and your insurer.",
    options: [
      { image: "/assets/cataract/monofocal.jpeg", title: "Standard Monofocal", tag: "SINGLE FOCUS LENS", text: "Designed to provide clear vision at one distance (usually far). Reading glasses may still be needed for close work.", bullets: ["Clear distance vision", "Insurance coverage varies", "Proven reliability"] },
      { image: "/assets/cataract/multifocal.jpeg", title: "Premium Multifocal", tag: "MULTIPLE FOCUS LENS", text: "Designed to support vision at multiple distances - near, intermediate, and far - and may reduce dependence on glasses.", bullets: ["Multiple focal points", "May reduce glasses dependency", "Enhanced lifestyle"] },
      { image: "/assets/cataract/edof-options.png", title: "EDOF IOL", tag: "EXTENDED DEPTH OF FOCUS", text: "Designed to provide a continuous range of vision from distance to intermediate; night-vision effects such as glare may vary between patients.", bullets: ["Distance to intermediate vision", "Night-vision effects vary", "Natural visual continuity"] },
      { image: "/assets/cataract/toric.jpeg", title: "Toric Lens", tag: "ASTIGMATISM CORRECTION", text: "Specially designed to help correct astigmatism and support clear distance vision in one procedure; outcomes vary by individual.", bullets: ["Designed to correct astigmatism", "May improve clarity", "Single procedure"] },
    ],
  },
  comparison: cataractComparison,
  benefits: {
    eyebrow: "ADVANTAGES",
    title: "Benefits of Modern",
    accent: "Cataract Surgery",
    body: "Many patients experience improved vision after surgery; results depend on the eye's overall health and other conditions.",
    items: [
      { image: "/assets/cataract/cataractbenefit2.jpeg", title: "Improved color perception" },
      { image: "/assets/cataract/cataractbenefit1.jpeg", title: "Clearer, brighter vision" },
      { image: "/assets/cataract/cataractbenefit3.jpeg", title: "Better quality of life" },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients who restored their vision with cataract surgery",
    items: [
      { quote: "My mother recently underwent cataract surgery at this hospital, and we had a wonderful experience. The surgery was successful, and her vision has improved significantly. The doctors, nurses, and entire staff were caring, professional, and explained everything clearly throughout the process. We are very happy with the results and sincerely thank the entire team.", name: "Vaibhav Bairagi", meta: "Patient Review" },
      { quote: "We had a great experience with Dr. Amit Solanki for cataract surgery. We came here for our parents' cataract surgery. He is a fantastic eye doctor and very humble. The surgery was handled with professionalism, and the hospital staff is equally supportive, polite, and cooperative.", name: "Sapna Sankhala", meta: "Patient Review" },
      { quote: "Wife's cataract surgery was a success! Thanks to Dr. Amit and his staff for the amazing care. If anyone is thinking of it, go for it — best decision ever.", name: "Ramesh Oza", meta: "Patient Review" },
      { quote: "I had my cataract surgery here. It was a great experience. Dr. explained everything clearly, and the service was very neat and clean. Staff was also very helpful and humble. Would definitely recommend.", name: "Rajesh Chouhan", meta: "Patient Review" },
      { quote: "Dr. Amit Solanki ji did the cataract operation for my mother so quickly and excellently, without any pain. I highly recommend any type of eye patients to Shanti Eye Tech, Palasia, Indore.", name: "Hemant Saini", meta: "Patient Review" },
      { quote: "My experience is very good, huge gratitude to Dr Amit sir and his staff, very happy with my cataract surgery.", name: "Girish Shrivastava", meta: "Patient Review" },
      { quote: "I had a great experience with Dr Amit Solanki and Shanti Eye Tech staff during my cataract surgery. Thank you Shanti Eye Tech for wonderful care.", name: "Radha Sawner", meta: "Patient Review" },
    ],
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Cataract Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Cataracts?",
    cardText: "Our cataract specialists are here to answer your questions and guide you through your treatment options.",
    items: [
      { question: "How do I know if I have cataracts?", answer: "Common signs include cloudy or blurry vision, difficulty seeing at night, sensitivity to light, seeing halos around lights, fading colors, and frequent changes in glasses prescription. A comprehensive eye examination can confirm cataracts and determine suitability for treatment." },
      { question: "Is cataract surgery safe?", answer: "Cataract surgery is one of the safest and most frequently performed surgical procedures in the world. As with any surgery, individual risks and expected outcomes should be discussed with your ophthalmologist after an eye examination." },
      { question: "How long does cataract surgery take?", answer: "Total time at the centre varies depending on preparation, the individual case and post-operative observation." },
      { question: "Will I need glasses after cataract surgery?", answer: "This depends on the type of intraocular lens (IOL) you choose, and is determined after an eye examination. Premium multifocal or trifocal lenses may reduce dependence on glasses for some patients." },
      { question: "What is the recovery time?", answer: "Recovery varies by patient. Many people notice clearer vision within a day or two, but your ophthalmologist will advise when you can safely resume specific activities." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "Our team can guide you through cataract evaluation and treatment options.",
    image: "/assets/cataract-chair.webp",
    serviceLabel: "treatment",
  },
};

const retinaContent: ServicePageContent = {
  kind: "retina",
  navService: "retina",
  hero: {
    eyebrow: "EARLY DETECTION & RETINA CARE",
    title: "Preserve Your Vision.",
    accent: "Cherish Every Moment.",
    text: "Retina care in Indore at Shanti Eye Tech focuses on early detection and expert evaluation to help protect your vision from serious, vision-threatening conditions.",
    image: "/assets/retina/retina-banner.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "97%", label: "Success Rate" },
      { value: "Essential", label: "Early Detection" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Patients Choose",
    accent: "Shanti Eye Tech",
    body: "Focused retinal evaluation, early detection and guidance for appropriate next steps",
    items: [
      { icon: "01", title: "Doctor-led eye care", text: "Every consultation handled by an experienced ophthalmologist" },
      { icon: "02", title: "Advanced technology", text: "Diagnostic evaluation to support retinal assessment and clinical decision-making" },
      { icon: "03", title: "Patient-friendly environment", text: "A calm, peaceful, reassuring space" },
      { icon: "04", title: "Personalised Attention", text: "Treatment plans tailored to your needs" },
      { icon: "05", title: "Affordable solutions", text: "Quality care at accessible prices" },
      { icon: "06", title: "Central Indore location", text: "Easily reachable from across the city" },
      { icon: "07", title: "Trained paramedical staff", text: "Qualified team supporting you" },
      { icon: "08", title: "Comprehensive services", text: "All major eye care under one roof" },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Retina?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "The retina is the <strong>light-sensitive tissue layer</strong> at the back of the eye that captures images and sends visual signals to the brain via the <strong>optic nerve</strong>.",
      "Some retinal damage can be irreversible, so early evaluation and appropriate treatment are important.",
    ],
    image: "/assets/retina/retina-exam.webp",
    retinaImages: {
      top: "/assets/retina/light_senstive.jpeg",
      bottom: "/assets/retina2.png",
    },
    callout: {
      title: "What Retina Care Involves",
      text: "At Shanti EyeTech, retina care includes dilated retinal examination to detect and diagnose retinal diseases and guide patients regarding further diagnostic procedures and treatment options.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider Evaluation?",
    body: "Watch out for these warning signs and schedule a comprehensive evaluation if they occur.",
    checks: ["Blurred or distorted vision", "Floaters or dark spots in vision", "Difficulty seeing in low light", "Loss of peripheral (side) vision", "Diabetes or high blood pressure"],
    note: "Sudden flashes of light, a sudden increase in floaters, or a curtain/shadow over vision require urgent eye assessment. If you experience any of these symptoms or have risk factors, schedule a comprehensive retinal examination promptly.",
    image: "/assets/retina/retina-exam.webp",
    warningImages: [
      { image: "/assets/retina/blurred-vision.jpg", label: "Blurred Vision" },
      { image: "/assets/retina/dark_spot.jpeg", label: "Dark Spots" },
      { image: "/assets/retina/low_vision.jpeg", label: "Low Light" },
      { image: "/assets/retina/side_vision.jpeg", label: "Side Vision" },
    ],
  },
  treatmentOptions: {
    eyebrow: "RETINA EVALUATION & GUIDANCE",
    title: "Our Retina",
    accent: "Evaluation & Guidance",
    body: "We provide dilated retinal examination to detect and diagnose retinal diseases and guide patients regarding further diagnostic procedures and treatment options.",
    options: [
      { image: "/assets/retina/retina-exam.webp", title: "Dilated Retinal Examination", tag: "EXAMINATION", text: "A detailed dilated examination to assess the retina and identify signs of retinal disease." },
      { image: "/assets/retina/dark_spot.jpeg", title: "Detection & Diagnosis", tag: "DIAGNOSIS", text: "Evaluation for conditions such as diabetic retinopathy, age-related macular degeneration, retinal tears and retinal detachment." },
      { image: "/assets/retina/blurred-vision.jpg", title: "Further Diagnostic Guidance", tag: "GUIDANCE", text: "Additional investigations may be advised depending on the examination findings." },
      { image: "/assets/retina/side_vision.jpeg", title: "Treatment Guidance / Referral", tag: "NEXT STEPS", text: "Based on the diagnosis, patients are guided regarding appropriate monitoring, treatment options or further specialist care where required." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Retina Care",
    body: "Timely assessment and treatment may help protect remaining vision and support daily activities.",
    items: [
      { image: "/assets/retina/active-life.webp", title: "Support for Daily Activities" },
      { image: "/assets/retina/preserve-vision.webp", title: "Protect Remaining Vision" },
      { image: "/assets/retina/independent-life.webp", title: "Reduced Risk of Vision Loss" },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "What Our Patients Say About Shanti EyeTech",
    items: commonTestimonials,
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Retina Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Retina Care?",
    cardText: "Our specialists are here to answer your questions and guide you through your treatment options.",
    items: [
      { question: "What symptoms need urgent retina evaluation?", answer: "Sudden flashes of light, a sudden increase in floaters, or a curtain/shadow over your vision need prompt eye assessment. Contact our team promptly if you notice any of these symptoms." },
      { question: "How does diabetes affect the retina?", answer: "Diabetes can damage the blood vessels in the retina, a condition known as diabetic retinopathy. Regular retinal examinations help detect changes early, when treatment may be most effective." },
      { question: "What happens during a retinal examination?", answer: "A retinal examination typically includes dilating the pupils and imaging or scanning the back of the eye to assess the retina, macula and blood vessels. Your ophthalmologist will explain the findings and any recommended next steps." },
      { question: "What happens if a retinal condition is detected?", answer: "After examination, your ophthalmologist may advise further diagnostic tests, monitoring, or appropriate treatment options depending on the condition. Where required, you may be guided for further specialist treatment." },
      { question: "Can retinal conditions affect both eyes?", answer: "Some retinal conditions, such as diabetic retinopathy, can affect both eyes, sometimes to different degrees. Regular examination of both eyes is generally recommended." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Start Your",
    accent: "Vision Journey",
    text: "If you notice sudden vision changes, floaters, flashes or distortion, book a retina evaluation promptly.",
    image: "/assets/retina-chair.webp",
    serviceLabel: "retina care",
    checkSubtitle: "Comprehensive retinal evaluation to help determine the appropriate next step.",
  },
};

const glaucomaContent: ServicePageContent = {
  kind: "glaucoma",
  navService: "glaucoma",
  hero: {
    eyebrow: "GLAUCOMA CARE",
    title: "Protect Your Vision with",
    accent: "Early Glaucoma Evaluation and Ongoing Care",
    text: "Glaucoma care in Indore at Shanti Eye Tech focuses on protecting your vision. Glaucoma can gradually damage the optic nerve, often without noticeable symptoms in its early stages, and timely screening, regular monitoring and appropriate treatment can help protect remaining vision.",
    image: "/assets/glaucoma/glaucoma-banner.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "Risk-Based", label: "Screening Guidance" },
      { value: "97%", label: "Patient Satisfaction" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti Eye Tech",
    accent: "for Glaucoma Care?",
    body: "Detailed assessment and long-term monitoring focused on protecting optic nerve health.",
    items: [
      { icon: "01", title: "Detailed Glaucoma Evaluation", text: "Assessment of eye pressure, optic nerve health and other risk factors to identify signs of glaucoma." },
      { icon: "02", title: "Optic Nerve Assessment", text: "Careful evaluation of the optic nerve to detect and monitor glaucoma-related changes." },
      { icon: "03", title: "Visual Field Testing", text: "Assessment of peripheral vision to identify functional vision loss associated with glaucoma." },
      { icon: "04", title: "Regular Progression Monitoring", text: "Follow-up examinations help track changes and determine whether treatment needs adjustment." },
      { icon: "05", title: "Personalised Treatment Planning", text: "Management is planned according to the type and severity of glaucoma, eye pressure and individual risk factors." },
      { icon: "06", title: "Medical, Laser & Surgical Care", text: "Treatment options may include eye drops, laser procedures or surgery depending on clinical findings." },
    ],
  },
  intro: {
    eyebrow: "UNDERSTANDING GLAUCOMA",
    title: "What is",
    accent: "Glaucoma?",
    backgroundImage: "/assets/whatisbg.png",
    paragraphs: [
      "Glaucoma is a group of eye conditions that damage the <strong>optic nerve</strong>, which carries vital visual information from the eye to the brain.",
      "In many cases, glaucoma is associated with <strong>increased intraocular pressure (IOP)</strong>, although it can also occur when eye pressure is within the normal range.",
      "Often called the <strong>'silent thief of sight,'</strong> early glaucoma produces few or no noticeable symptoms. <strong>Routine comprehensive eye examinations</strong> are essential to protect against irreversible vision loss.",
    ],
    image: "/assets/glaucoma/whatisglaucoma.png",
    callout: {
      title: "Important",
      text: "Damage to the optic nerve from glaucoma cannot currently be reversed. Treatment aims to slow or prevent further vision loss.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Glaucoma Evaluation?",
    body: "The following are risk factors or reasons to schedule an assessment, not a diagnosis:",
    backgroundImage: "/assets/cataract/considersurgerybg.jpeg",
    checks: [
      "Family history of glaucoma",
      "Increased eye pressure",
      "Age-related increase in glaucoma risk",
      "Diabetes or certain other medical conditions",
      "Long-term corticosteroid use",
      "Previous eye injury or eye surgery",
      "Gradual loss of peripheral vision",
      "Halos around lights or unexplained visual changes",
    ],
    note: "Sudden severe eye pain, redness, headache, blurred vision, halos, nausea or vomiting requires urgent medical attention. Do not wait for an online appointment response.",
    image: "/assets/eye-check.webp",
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Glaucoma Care &",
    accent: "Treatment Options",
    body: "Glaucoma treatment focuses on controlling eye pressure and reducing the risk of further optic nerve damage. The appropriate approach depends on the type and stage of glaucoma.",
    options: [
      { image: "/assets/glaucoma/medical_management.png", title: "Medical Management", tag: "Eye Pressure Control", text: "Prescription eye drops or other medications may be used to lower eye pressure and help reduce the risk of further optic nerve damage." },
      { image: "/assets/glaucoma/laser_treatment.png", title: "Laser Treatment", tag: "Targeted Treatment", text: "Laser procedures may be recommended for certain types of glaucoma to improve fluid drainage or help control pressure within the eye." },
      { image: "/assets/glaucoma/glaucoma_surgery.png", title: "Glaucoma Surgery", tag: "Advanced Glaucoma Care", text: "When medications or laser treatment do not provide sufficient pressure control, surgical treatment may be considered to help lower eye pressure." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Glaucoma Care",
    body: "Timely glaucoma care helps protect remaining vision through careful pressure control and ongoing monitoring.",
    items: [
      { image: "/assets/glaucoma/protect_remaining.png", title: "Protect Remaining Vision", description: "Aim to protect remaining vision through pressure control and ongoing monitoring." },
      { image: "/assets/glaucoma/human-tonometry.jpg", title: "Control Eye Pressure", description: "Treatment aims to maintain eye pressure at a level considered appropriate for the individual patient." },
      { image: "/assets/glaucoma/monitor_optic.png", title: "Monitor Optic Nerve Health", description: "Regular examinations allow changes in the optic nerve to be identified and tracked over time." },
      { image: "/assets/glaucoma/preserve_peripheral.png", title: "Preserve Peripheral Vision", description: "Controlling glaucoma progression can help protect functional side vision for as long as possible." },
      { image: "/assets/glaucoma/long_term.png", title: "Plan Long-Term Eye Care", description: "Because glaucoma usually requires ongoing monitoring, regular follow-up helps treatment evolve with the condition." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "What Our Patients Say About Shanti EyeTech",
    items: generalCareTestimonials,
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Glaucoma Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Glaucoma?",
    cardText: "Our glaucoma care team can help you understand screening, risk factors, monitoring and treatment options.",
    items: [
      { question: "Can glaucoma be cured?", answer: "Damage to the optic nerve caused by glaucoma is generally irreversible. However, treatment can lower eye pressure and help slow or prevent further damage." },
      { question: "Does glaucoma always cause symptoms?", answer: "No. Open-angle glaucoma, the most common form, often develops gradually without noticeable symptoms during its early stages." },
      { question: "Is high eye pressure the same as glaucoma?", answer: "No. Some people have elevated eye pressure without optic nerve damage, while others can develop glaucoma despite pressure readings within the statistically normal range. Diagnosis requires a complete eye assessment." },
      { question: "Who should be screened for glaucoma?", answer: "Regular comprehensive eye examinations become particularly important with increasing age and for people with risk factors such as a family history of glaucoma, elevated eye pressure or certain medical and ocular conditions." },
      { question: "Will I need glaucoma treatment for life?", answer: "Glaucoma is usually a long-term condition requiring ongoing monitoring. The type and duration of treatment depend on the individual patient and how the condition responds." },
      { question: "Does every glaucoma patient need surgery?", answer: "No. Many patients are managed with medication or laser treatment. Surgery may be considered when adequate pressure control is not achieved or when clinically appropriate." },
      { question: "Can lost vision from glaucoma return after treatment?", answer: "Existing glaucoma-related optic nerve damage usually cannot be reversed. This is why early detection and prevention of additional damage are especially important." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Don't Wait for Glaucoma",
    accent: "to Affect Your Vision",
    text: "Glaucoma can progress quietly. If you have increased eye pressure, a family history of glaucoma or other risk factors, a comprehensive glaucoma evaluation can help assess your optic nerve health and determine whether monitoring or treatment is needed.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "glaucoma care",
    badgeTitle: "Early",
    badgeSubtitle: "Detection Matters",
    checkTitle: "Request a Glaucoma Evaluation",
    checkSubtitle: "Comprehensive evaluation for pressure, optic nerve health and risk factors",
  },
};

const squintContent: ServicePageContent = {
  kind: "squint",
  navService: "squint",
  hero: {
    eyebrow: "SQUINT TREATMENT",
    title: "Helping Eyes Work",
    accent: "Better Together",
    text: "Squint, or strabismus, occurs when both eyes do not remain properly aligned and look in the same direction. Early evaluation can help identify the cause and determine the appropriate treatment, particularly in children.",
    image: "/assets/squint/squint-banner.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "20+ yrs", label: "Specialized Care" },
      { value: "97%", label: "Patient Satisfaction" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti Eye Tech",
    accent: "for Squint Treatment?",
    body: "Specialized eye alignment evaluation and compassionate care for children and adults.",
    items: [
      { icon: "01", title: "Detailed Eye Alignment Evaluation", text: "Assessment of eye position, movement and coordination to understand the type and extent of squint." },
      { icon: "02", title: "Child-Friendly Eye Care", text: "A comfortable approach to examining and managing squint in children." },
      { icon: "03", title: "Vision & Amblyopia Assessment", text: "Evaluation for associated vision problems, including lazy eye, where clinically relevant." },
      { icon: "04", title: "Personalised Treatment Planning", text: "Treatment recommendations based on age, vision, eye alignment and the underlying cause." },
      { icon: "05", title: "Non-Surgical & Surgical Options", text: "Management may include glasses, amblyopia treatment or surgery depending on individual findings." },
      { icon: "06", title: "Regular Follow-Up Care", text: "Ongoing assessment to monitor vision development and eye alignment." },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Squint?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "Squint, medically known as <strong>strabismus</strong>, is a condition in which the two eyes are <strong>not properly aligned</strong> and may point in different directions.",
      "One eye may look straight while the other turns inward, outward, upward or downward. The deviation may be present constantly or appear intermittently.",
      "In children, timely assessment is vital because persistent misalignment can interfere with normal visual development and lead to <strong>amblyopia (lazy eye)</strong> and loss of <strong>binocular depth perception</strong>.",
    ],
    image: "/assets/squint/whatissquint1.png",
    retinaImages: {
      top: "/assets/squint/whatissquint1.png",
      bottom: "/assets/squint/whatissquint2.png",
    },
    callout: {
      title: "Squint Care",
      text: "focuses on assessing eye alignment, preserving visual function, and guiding timely intervention for both children and adults.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Squint Evaluation?",
    body: "Watch Out for These Signs",
    backgroundImage: "/assets/retina/retina_optionsbg.jpeg",
    checks: [
      "One eye turning inward or outward",
      "Eyes that do not appear properly aligned",
      "Squint that appears intermittently",
      "Child closing or covering one eye",
      "Tilting or turning the head while looking at objects",
      "Difficulty judging depth or coordinating both eyes",
      "Double vision, particularly in adults",
      "An eye deviation that appears suddenly",
    ],
    note: "A sudden new squint or new double vision in an adult should be medically evaluated promptly.",
    image: "/assets/squint/whatissquint1.png",
    warningImages: [
      { image: "/assets/squint/blur_vision.png", label: "Blurred Vision" },
      { image: "/assets/squint/intermittent_squint.png", label: "Intermittent Squint" },
      { image: "/assets/squint/head_tilting.png", label: "Head Tilting" },
      { image: "/assets/squint/double_vision.png", label: "Double Vision" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Squint Care &",
    accent: "Treatment Options",
    body: "Care is planned according to the type of squint, its cause, age and its effect on vision.",
    options: [
      { image: "/assets/squint/glasses_correction.png", title: "Glasses / Vision Correction", tag: "VISION CORRECTION", text: "Prescription glasses may help improve vision and, in certain types of squint, can also improve eye alignment." },
      { image: "/assets/squint/amblyopia_treatment.png", title: "Amblyopia Treatment", tag: "LAZY EYE CARE", text: "When one eye has reduced vision, treatment may be recommended to encourage visual development in the weaker eye." },
      { image: "/assets/squint/squint_surgery.png", title: "Squint Surgery", tag: "EYE ALIGNMENT", text: "When clinically indicated, surgery can adjust the eye muscles to improve the alignment of the eyes." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Squint Care",
    body: "Support visual development and eye alignment.",
    items: [
      { image: "/assets/squint/support_visual.png", title: "Support Visual Development", description: "Early care can be particularly important while a child's visual system is still developing." },
      { image: "/assets/squint/improve_eye.png", title: "Improve Eye Alignment", description: "Appropriate management can help improve the position and coordination of the eyes." },
      { image: "/assets/squint/address_associated.png", title: "Address Associated Lazy Eye", description: "Identifying amblyopia early provides an opportunity to manage reduced vision in the affected eye." },
      { image: "/assets/squint/improve_binocular.png", title: "Improve Binocular Function", description: "Where possible, treatment aims to support the ability of both eyes to work together." },
      { image: "/assets/squint/visual_confidence.png", title: "Build Visual Confidence", description: "Improved alignment and visual function can make everyday visual activities more comfortable." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "Real experiences from patients and parents who chose squint evaluation and care",
    items: commonTestimonials,
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Squint Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Squint?",
    cardText: "Our eye care team can help you understand squint evaluation, treatment options and care plans.",
    items: [
      { question: "What causes squint?", answer: "Squint can have several causes, including problems with eye-muscle control, refractive errors, differences in vision between the eyes or other underlying eye or neurological conditions." },
      { question: "Is squint common in children?", answer: "Squint can occur during childhood. Any persistent or recurring eye deviation should be evaluated rather than assuming the child will simply outgrow it." },
      { question: "Can squint cause lazy eye?", answer: "Yes. In some children, the brain may begin relying more heavily on one eye, which can result in reduced vision in the deviating eye." },
      { question: "Does every squint require surgery?", answer: "No. Treatment depends on the type and cause of the squint. Some patients may require glasses or amblyopia treatment, while surgery may be appropriate for others." },
      { question: "Can adults undergo squint treatment?", answer: "Yes. Adults with squint can also be evaluated for appropriate treatment depending on the cause, symptoms and eye alignment." },
      { question: "When should my child have a squint evaluated?", answer: "If you notice persistent, frequent or recurring misalignment of the eyes, an eye examination should be arranged. Sudden-onset squint should be assessed promptly." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Take the First Step Towards",
    accent: "Better Eye Alignment",
    text: "If you notice that your or your child’s eyes are not properly aligned, an eye examination can help identify the cause and determine the appropriate next step.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "squint treatment",
    badgeTitle: "Early",
    badgeSubtitle: "Evaluation Matters",
    checkTitle: "Book a Squint Evaluation",
    checkSubtitle: "Comprehensive assessment for eye position, movement and visual development",
  },
};

// Content sourced from the sibling marketing site
// (shanti-eye-tech-website-frontend/src/pages/treatments/pediatric-eye-care.jsx
// + constant/treatmentContent.js#pediatricEyeCare), rebuilt onto website-v3's
// section components. `kind` is deliberately "squint" (not a new "pediatric"
// kind) so this page picks up the exact same section styling/layout branch
// as the Squint Treatment page (retina-style intro, full warning-signs
// eligibility layout, etc.) — the ask was "same UI section as squint" for
// this page, and reusing the kind avoids duplicating ~9 components' worth of
// per-kind CSS for a visually-identical layout.
const pediatricContent: ServicePageContent = {
  kind: "squint",
  navService: "squint",
  hero: {
    eyebrow: "PEDIATRIC EYE CARE",
    title: "Protect Their Future.",
    accent: "Every Little Moment Matters.",
    text: "Pediatric eye care in Indore at Shanti Eye Tech offers expert, child-friendly evaluations to help support your child's vision and eye health.",
    image: "/assets/pediatric/banner-new.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "20+ yrs", label: "Trusted Care" },
      { value: "97%", label: "Patient Satisfaction" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti Eye Tech",
    accent: "for Pediatric Eye Care?",
    body: "Gentle, specialized eye care for infants, children and teenagers.",
    items: [
      { icon: "01", title: "Child-Friendly Eye Exams", text: "Comfortable, comprehensive evaluations designed to put young patients at ease." },
      { icon: "02", title: "Early Detection Focus", text: "Timely eye examinations to catch vision problems before they affect learning and development." },
      { icon: "03", title: "Orthoptic Exercises", text: "May be advised for selected binocular vision disorders to improve eye coordination." },
      { icon: "04", title: "Myopia Management", text: "Myopia-management options may be considered for suitable children to help manage progression." },
      { icon: "05", title: "Experienced Specialists", text: "Experienced ophthalmology care for children's eye health and vision development." },
      { icon: "06", title: "Ongoing Follow-Up Care", text: "Regular monitoring to track your child's vision development over time." },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Pediatric Eye Care?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "Pediatric eye care focuses on the <strong>eye health and vision development</strong> of infants, children, and teenagers. Early eye examinations help detect and treat vision problems that can affect learning, development, and quality of life.",
      "<strong>Good vision in childhood</strong> lays the foundation for a bright and successful future. Early detection and treatment make all the difference.",
    ],
    image: "/assets/pediatric/whatis1.png",
    retinaImages: {
      top: "/assets/pediatric/whatis1.png",
      bottom: "/assets/pediatric/whatis2.png",
    },
    callout: {
      title: "What Pediatric Eye Care Involves",
      text: "Pediatric eye care focuses on healthy vision and happy childhood, from comprehensive exams to age-appropriate treatment options.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider an Eye Checkup?",
    body: "Watch Out for These Signs",
    backgroundImage: "/assets/retina/retina_optionsbg.jpeg",
    checks: [
      "Squinting or tilting the head",
      "Sitting very close to screens or TV",
      "Frequent rubbing of the eyes",
      "Complaints of headache or eye strain",
      "Difficulty reading or concentrating",
    ],
    note: "If you notice any of these signs, schedule a comprehensive eye examination for your child promptly. A noticeable eye turn, white pupil, persistent redness or sudden vision change needs prompt professional assessment.",
    image: "/assets/pediatric/pediatric.png",
    warningImages: [
      { image: "/assets/pediatric/signs_1.png", label: "Covering One Eye" },
      { image: "/assets/pediatric/signs_3.png", label: "Sitting Close to Screens" },
      { image: "/assets/pediatric/signs_2.png", label: "Rubbing Eyes" },
      { image: "/assets/pediatric/signs_4.png", label: "Reading Difficulty" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Pediatric Eye Care &",
    accent: "Treatment Options",
    body: "Specialized care for healthy vision and happy childhood. Recommendations depend on your child's age, prescription and eye findings.",
    options: [
      { image: "/assets/pediatric/options1.png", title: "Comprehensive Eye Exams", tag: "EARLY DETECTION", text: "Thorough eye evaluations to detect vision issues early." },
      { image: "/assets/pediatric/options2.png", title: "Orthoptic Exercises", tag: "EYE COORDINATION", text: "May be advised for selected binocular vision disorders to improve eye coordination." },
      { image: "/assets/pediatric/options3.png", title: "Myopia Management", tag: "ASSESSMENT-LED", text: "Myopia-management options may be considered for suitable children to help manage progression, depending on age, prescription and eye findings." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Early",
    accent: "Pediatric Eye Care",
    body: "Clear, comfortable vision can support a child's daily activities and learning.",
    items: [
      { image: "/assets/pediatric/benefits1.png", title: "Long-term Healthy Vision" },
      { image: "/assets/pediatric/benefits2.png", title: "Support for Learning" },
      { image: "/assets/pediatric/benefits3.png", title: "Comfortable Daily Vision" },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "What Our Patients Say About Shanti EyeTech",
    items: generalCareTestimonials,
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Pediatric Eye Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Your Child's Eyes?",
    cardText: "Our pediatric eye care team is here to answer your questions and help you understand evaluation and treatment options.",
    items: [
      { question: "When should my child have their first eye exam?", answer: "Children should receive vision screening at recommended health visits. A comprehensive eye examination may be advised if screening is failed, symptoms are noticed, or there is a relevant family or medical history." },
      { question: "What signs suggest my child has a vision problem?", answer: "Common signs include squinting, closing one eye, frequent headaches, eye strain, rubbing the eyes, losing place while reading, or difficulty concentrating at school. A noticeable eye turn, white pupil, persistent redness or sudden vision change needs prompt professional assessment." },
      { question: "Can screen time affect children's eyes?", answer: "Sitting very close to a screen or television may be a sign that a child needs a vision check, rather than proof that screens caused the problem. Regular breaks, proper lighting, outdoor time, and routine eye checks are generally recommended." },
      { question: "What is myopia management?", answer: "Myopia management refers to options that may be considered for suitable children to help manage the progression of nearsightedness, based on individual assessment. Suitability and approach depend on the child's age, prescription and eye findings." },
      { question: "Is pediatric eye testing painful?", answer: "No, pediatric eye testing is generally comfortable and child friendly. Most tests are non-invasive and designed to help children feel relaxed during the visit." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE FIRST STEP",
    title: "Take the First Step Towards",
    accent: "Healthy Little Eyes",
    text: "Early eye care can shape a lifetime of clear vision and confidence. Schedule a comprehensive pediatric eye examination for your child today.",
    // The child is positioned right-of-center in this source photo — the
    // default centered crop in this smaller image box was mostly showing
    // background/teddy bear with the child cut off at the edge.
    image: "/assets/pediatric/hero_banner.png",
    imagePosition: "80% center",
    serviceLabel: "pediatric eye care",
    badgeTitle: "Early",
    badgeSubtitle: "Care Matters",
    checkTitle: "Request a Pediatric Eye Evaluation",
    checkSubtitle: "Comprehensive evaluation for your child's vision and eye health",
  },
};

const keratoconusContent: ServicePageContent = {
  kind: "keratoconus",
  navService: "keratoconus",
  hero: {
    eyebrow: "KERATOCONUS CARE",
    title: "Protect Your Cornea.",
    accent: "Preserve Clearer Vision.",
    text: "Keratoconus causes the cornea to gradually thin and change shape, leading to distorted or blurred vision. Early evaluation and appropriate management can help monitor its progression and protect visual quality.",
    image: "/assets/keratoconus/keratoconus-banner.png",
    metrics: [
      { value: "49K+", label: "Successful Procedures" },
      { value: "20+ yrs", label: "Specialized Care" },
      { value: "97%", label: "Patient Satisfaction" },
    ],
    reviewedBy: "Dr. Amit N. Solanki, MBBS, DOMS, DNB, FAECS",
  },
  whyChoose: {
    eyebrow: "WHY CHOOSE US",
    title: "Why Choose Shanti Eye Tech",
    accent: "for Keratoconus Care?",
    body: "Detailed corneal evaluation and advanced monitoring to protect visual quality.",
    items: [
      { icon: "01", title: "Detailed Corneal Evaluation", text: "Careful assessment of the cornea to understand its shape, thickness and condition." },
      { icon: "02", title: "Early Detection & Monitoring", text: "Regular evaluation can help identify changes and monitor whether keratoconus is progressing." },
      { icon: "03", title: "Advanced Corneal Imaging", text: "Diagnostic assessment using corneal mapping and other investigations when clinically required." },
      { icon: "04", title: "Personalised Treatment Planning", text: "Care recommendations based on the stage of keratoconus, visual needs and progression." },
      { icon: "05", title: "Vision Rehabilitation Options", text: "Guidance on suitable glasses or contact-lens options depending on the condition." },
      { icon: "06", title: "Progression-Control Treatment", text: "Corneal cross-linking may be considered in appropriate patients to help slow or halt progression." },
    ],
  },
  intro: {
    eyebrow: "ESSENTIAL KNOWLEDGE",
    title: "What is",
    accent: "Keratoconus?",
    backgroundImage: "/assets/retina/retinabg.jpeg",
    paragraphs: [
      "Keratoconus is a progressive condition in which the normally round cornea becomes thinner and <strong>gradually bulges into an irregular cone-like shape</strong>.",
      "The cornea is the transparent front surface of the eye and plays an important role in focusing light. When its shape becomes irregular, light fails to focus sharply on the retina, resulting in <strong>distorted and blurred vision</strong>.",
      "The condition often begins during teenage or early adult years. Corneal cross-linking may help slow or halt progression in suitable cases, while spectacles or specialised contact lenses may help improve visual clarity.",
    ],
    image: "/assets/keratoconus/whatiskeratoconus1.png",
    retinaImages: {
      top: "/assets/keratoconus/whatiskeratoconus2.png",
      bottom: "/assets/keratoconus/whatiskeratoconus1.png",
    },
    callout: {
      title: "Keratoconus Care",
      text: "focuses on detailed corneal assessment, preserving functional vision, and halting progression through timely management.",
    },
  },
  eligibility: {
    eyebrow: "WARNING SIGNS",
    title: "When Should You",
    accent: "Consider a Keratoconus Evaluation?",
    body: "Watch Out for These Signs",
    backgroundImage: "/assets/retina/retina_optionsbg.jpeg",
    checks: [
      "Frequent changes in spectacle power",
      "Increasing blurred or distorted vision",
      "Difficulty seeing clearly even with glasses",
      "Increased sensitivity to bright light or glare",
      "Halos around lights, especially at night",
      "Ghosting or multiple images around objects",
      "Increasing astigmatism",
      "Family history of keratoconus",
    ],
    note: "If your spectacle prescription is changing frequently or your vision remains distorted despite correction, a detailed corneal evaluation may be recommended.",
    image: "/assets/keratoconus/frequent_power.png",
    warningImages: [
      { image: "/assets/keratoconus/frequent_power.png", label: "Frequent Power Change" },
      { image: "/assets/keratoconus/blurred_vision.png", label: "Blurred / Distorted Vision" },
      { image: "/assets/keratoconus/light_sesitivity.png", label: "Light Sensitivity" },
      { image: "/assets/keratoconus/halos.png", label: "Halos & Glare" },
      { image: "/assets/keratoconus/astigmatism.png", label: "Increasing Astigmatism" },
    ],
  },
  treatmentOptions: {
    eyebrow: "TREATMENT OPTIONS",
    title: "Our Keratoconus Care &",
    accent: "Treatment Options",
    body: "Treatment depends on the severity of the condition, quality of vision and whether the keratoconus is progressing.",
    options: [
      { image: "/assets/keratoconus/glasses.png", title: "Glasses & Contact Lenses", tag: "VISION CORRECTION", text: "In earlier stages, spectacles or specialised contact lenses may help improve visual clarity by correcting the refractive error caused by the irregular cornea." },
      { image: "/assets/keratoconus/corneal-cross.png", title: "Corneal Cross-Linking (CXL)", tag: "PROGRESSION CONTROL", text: "Cross-linking is used in appropriate cases of progressive keratoconus to strengthen the corneal tissue and help reduce further progression." },
      { image: "/assets/keratoconus/advanced-corneal.png", title: "Intacs Inserts", tag: "SELECTED CASES", text: "Thin, semi-circular implants placed within the cornea to help flatten its shape and improve vision in selected cases." },
    ],
  },
  benefits: {
    eyebrow: "KEY BENEFITS",
    title: "Benefits of Timely",
    accent: "Keratoconus Care",
    body: "Detect progression early and preserve clear, functional vision.",
    items: [
      { image: "/assets/keratoconus/detect_progression.png", title: "Detect Progression Early", description: "Regular corneal evaluation can help identify changes before significant progression occurs." },
      { image: "/assets/keratoconus/preserve_functional.png", title: "Preserve Functional Vision", description: "Appropriate correction and management can help patients maintain better usable vision." },
      { image: "/assets/keratoconus/control_progression.png", title: "Control Progression", description: "In suitable progressive cases, cross-linking can help stabilise the cornea and reduce further deterioration." },
      { image: "/assets/keratoconus/improve_visual.png", title: "Improve Visual Quality", description: "Appropriate glasses or contact lenses can help manage blur and distortion caused by the irregular cornea." },
      { image: "/assets/keratoconus/plan-long-term.png", title: "Plan Long-Term Corneal Care", description: "Regular monitoring allows treatment decisions to be adjusted as the condition changes." },
    ],
  },
  testimonials: {
    eyebrow: "PATIENT STORIES",
    title: "You're Not Alone,",
    accent: "Hear From Others Like You",
    body: "What Our Patients Say About Shanti EyeTech",
    items: commonTestimonials,
  },
  faq: {
    eyebrow: "COMMON QUESTIONS",
    title: "Keratoconus Care",
    accent: "FAQs",
    cardTitle: "Have Questions About Keratoconus?",
    cardText: "Our eye-care team can help you understand keratoconus evaluation, monitoring and treatment options.",
    items: [
      { question: "What causes keratoconus?", answer: "The exact cause is not always known. Genetic and environmental factors may contribute, and keratoconus can sometimes run in families." },
      { question: "Does keratoconus always get worse?", answer: "Not necessarily. Progression varies between individuals. This is why periodic corneal evaluation and comparison of measurements are important." },
      { question: "Can glasses correct keratoconus?", answer: "Glasses may provide adequate vision in early keratoconus. As corneal irregularity increases, specialised contact lenses may provide better visual correction for some patients." },
      { question: "What is corneal cross-linking?", answer: "Corneal cross-linking is a procedure designed to strengthen corneal tissue. It is primarily intended to reduce or stop further progression rather than simply remove spectacle power." },
      { question: "Can LASIK be performed if I have keratoconus?", answer: "Keratoconus generally makes standard corneal laser vision-correction procedures such as LASIK unsuitable. A detailed corneal assessment is necessary before considering any refractive procedure." },
      { question: "Can keratoconus affect both eyes?", answer: "Yes. Keratoconus commonly affects both eyes, although its severity and progression may differ between them." },
      { question: "Why is early diagnosis important?", answer: "Detecting keratoconus early allows the ophthalmologist to monitor progression and consider treatment before more significant corneal changes occur." },
    ],
  },
  appointment: {
    eyebrow: "TAKE THE NEXT STEP",
    title: "Take the Next Step Towards",
    accent: "Protecting Your Cornea",
    text: "If you are experiencing frequent power changes, distorted vision or have been diagnosed with keratoconus, a detailed corneal evaluation can help determine its current stage and the appropriate next step.",
    image: "/assets/lasik/vision_journey.jpeg",
    serviceLabel: "keratoconus care",
    badgeTitle: "Early",
    badgeSubtitle: "Diagnosis Matters",
    checkTitle: "Book a Corneal Evaluation",
    checkSubtitle: "Comprehensive assessment of corneal shape, thickness and visual quality",
  },
};

export const servicePages = {
  cataract: cataractContent,
  classic: classicContent,
  lasik: classicContent,
  retina: retinaContent,
  glaucoma: glaucomaContent,
  squint: squintContent,
  keratoconus: keratoconusContent,
  pediatric: pediatricContent,
};








